# Generated by Django 6.0.1 on 2026-01-11 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("HOURLY", "시간당"),
                            ("SHIFT", "교대당"),
                            ("DAILY", "일일"),
                            ("BATCH", "배치당"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sample_size", models.IntegerField(default=5)),
                ("subgroup_size", models.IntegerField(default=5)),
                (
                    "sampling_method",
                    models.CharField(
                        choices=[
                            ("ALL", "전수 검사"),
                            ("RANDOM", "랜덤 샘플링"),
                            ("PERIODIC", "주기적 샘플링"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "characteristic",
                    models.CharField(
                        help_text="검사 특성 (예: 직경, 무게)", max_length=100
                    ),
                ),
                ("measurement_method", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spc_inspection_plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=200)),
                ("usl", models.FloatField(help_text="Upper Specification Limit")),
                ("lsl", models.FloatField(help_text="Lower Specification Limit")),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(default="mm", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spc_product",
                "ordering": ["product_code"],
            },
        ),
        migrations.CreateModel(
            name="ControlChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("XBAR_R", "X-bar & R Chart"),
                            ("XBAR_S", "X-bar & S Chart"),
                            ("I_MR", "Individual & Moving Range Chart"),
                            ("P_CHART", "p-Chart (불량률)"),
                            ("NP_CHART", "np-Chart (불량수)"),
                            ("C_CHART", "c-Chart (결점수)"),
                            ("U_CHART", "u-Chart (단위당 결점수)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "xbar_ucl",
                    models.FloatField(
                        blank=True, help_text="X-bar Upper Control Limit", null=True
                    ),
                ),
                (
                    "xbar_cl",
                    models.FloatField(
                        blank=True, help_text="X-bar Center Line", null=True
                    ),
                ),
                (
                    "xbar_lcl",
                    models.FloatField(
                        blank=True, help_text="X-bar Lower Control Limit", null=True
                    ),
                ),
                (
                    "r_ucl",
                    models.FloatField(
                        blank=True, help_text="R Upper Control Limit", null=True
                    ),
                ),
                (
                    "r_cl",
                    models.FloatField(blank=True, help_text="R Center Line", null=True),
                ),
                (
                    "r_lcl",
                    models.FloatField(
                        blank=True, help_text="R Lower Control Limit", null=True
                    ),
                ),
                (
                    "s_ucl",
                    models.FloatField(
                        blank=True, help_text="S Upper Control Limit", null=True
                    ),
                ),
                (
                    "s_cl",
                    models.FloatField(blank=True, help_text="S Center Line", null=True),
                ),
                (
                    "s_lcl",
                    models.FloatField(
                        blank=True, help_text="S Lower Control Limit", null=True
                    ),
                ),
                ("p_ucl", models.FloatField(blank=True, null=True)),
                ("p_cl", models.FloatField(blank=True, null=True)),
                ("p_lcl", models.FloatField(blank=True, null=True)),
                ("subgroup_size", models.IntegerField(default=5)),
                (
                    "num_subgroups",
                    models.IntegerField(
                        default=25, help_text="한계선 계산에 사용된 부분군 수"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_charts",
                        to="spc.inspectionplan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_charts",
                        to="spc.product",
                    ),
                ),
            ],
            options={
                "db_table": "spc_control_chart",
                "ordering": ["-created_at"],
                "unique_together": {("product", "chart_type", "is_active")},
            },
        ),
        migrations.CreateModel(
            name="ProcessCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cp", models.FloatField(help_text="Process Capability Index")),
                (
                    "cpk",
                    models.FloatField(help_text="Process Capability Index (adjusted)"),
                ),
                ("cpu", models.FloatField(help_text="Upper Capability Index")),
                ("cpl", models.FloatField(help_text="Lower Capability Index")),
                (
                    "pp",
                    models.FloatField(
                        blank=True, help_text="Process Performance Index", null=True
                    ),
                ),
                (
                    "ppk",
                    models.FloatField(
                        blank=True,
                        help_text="Process Performance Index (adjusted)",
                        null=True,
                    ),
                ),
                ("mean", models.FloatField()),
                ("std_deviation", models.FloatField()),
                ("sample_size", models.IntegerField()),
                ("is_normal", models.BooleanField(default=True)),
                ("normality_test_statistic", models.FloatField(blank=True, null=True)),
                ("normality_test_p_value", models.FloatField(blank=True, null=True)),
                ("analysis_start", models.DateTimeField()),
                ("analysis_end", models.DateTimeField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "control_chart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.controlchart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="spc.product",
                    ),
                ),
            ],
            options={
                "db_table": "spc_process_capability",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.AddField(
            model_name="inspectionplan",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_plans",
                to="spc.product",
            ),
        ),
        migrations.CreateModel(
            name="QualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_value", models.FloatField()),
                ("sample_number", models.IntegerField(help_text="샘플 번호")),
                ("subgroup_number", models.IntegerField(help_text="부분군 번호")),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("measured_by", models.CharField(max_length=100)),
                ("machine_id", models.CharField(blank=True, max_length=50)),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("is_within_spec", models.BooleanField(default=True)),
                ("is_within_control", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.inspectionplan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="spc.product",
                    ),
                ),
            ],
            options={
                "db_table": "spc_quality_measurement",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "일일 보고서"),
                            ("WEEKLY", "주간 보고서"),
                            ("MONTHLY", "월간 보고서"),
                            ("CUSTOM", "사용자 정의"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("summary", models.TextField(blank=True)),
                ("key_findings", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("total_measurements", models.IntegerField(default=0)),
                ("out_of_spec_count", models.IntegerField(default=0)),
                ("out_of_control_count", models.IntegerField(default=0)),
                ("alert_count", models.IntegerField(default=0)),
                (
                    "report_file",
                    models.CharField(
                        blank=True, help_text="PDF/Excel 파일 경로", max_length=500
                    ),
                ),
                ("generated_by", models.CharField(max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(related_name="reports", to="spc.product"),
                ),
            ],
            options={
                "db_table": "spc_quality_report",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="RunRuleViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("RULE_1", "Rule 1: 관리 한계 벗어남"),
                            ("RULE_2", "Rule 2: 9개 연속 중심선 한쪽"),
                            ("RULE_3", "Rule 3: 6개 연속 증가/감소"),
                            ("RULE_4", "Rule 4: 14개 연속 교대 상승/하강"),
                            ("RULE_5", "Rule 5: 3개 중 2개가 2σ 벗어남"),
                            ("RULE_6", "Rule 6: 5개 중 4개가 1σ 벗어남"),
                            ("RULE_7", "Rule 7: 15개 연속 1σ 이내"),
                            ("RULE_8", "Rule 8: 8개 연속 1σ 벗어남"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.IntegerField(
                        default=1, help_text="1=낮음, 2=보통, 3=높음, 4=긴급"
                    ),
                ),
                (
                    "violation_data",
                    models.JSONField(
                        default=dict, help_text="위반 관련 데이터 (인덱스, 값 등)"
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "control_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="spc.controlchart",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="spc.qualitymeasurement",
                    ),
                ),
            ],
            options={
                "db_table": "spc_run_rule_violation",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("OUT_OF_SPEC", "규격 이탈"),
                            ("OUT_OF_CONTROL", "관리 한계 이탈"),
                            ("RUN_RULE", "Run Rule 위반"),
                            ("TREND", "트렌드 경고"),
                            ("PREDICTION", "AI 예측 경고"),
                            ("CAPABILITY", "공정능력 저하"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "낮음"), (2, "보통"), (3, "높음"), (4, "긴급")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "신규"),
                            ("ACKNOWLEDGED", "확인됨"),
                            ("INVESTIGATING", "조사중"),
                            ("RESOLVED", "해결됨"),
                            ("CLOSED", "종료됨"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=100)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=100)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=100)),
                ("resolution_notes", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("alert_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="spc.product",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.qualitymeasurement",
                    ),
                ),
                (
                    "violation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.runruleviolation",
                    ),
                ),
            ],
            options={
                "db_table": "spc_quality_alert",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qualitymeasurement",
            index=models.Index(
                fields=["product", "measured_at"], name="spc_quality_product_1da1fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitymeasurement",
            index=models.Index(
                fields=["subgroup_number"], name="spc_quality_subgrou_a33755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityalert",
            index=models.Index(
                fields=["product", "status"], name="spc_quality_product_03f827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityalert",
            index=models.Index(
                fields=["created_at"], name="spc_quality_created_015494_idx"
            ),
        ),
    ]
