# Generated by Django 6.0.1 on 2026-01-11 15:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementInstrumentMaster",
            fields=[
                ("instrument_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "instrument_cd",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="기구코드",
                    ),
                ),
                (
                    "instrument_nm",
                    models.CharField(max_length=200, verbose_name="기구명"),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("CALIPER", "노규자"),
                            ("MICROMETER", "마이크로미터"),
                            ("CMM", "3차원측정기"),
                            ("SCALE", "저울"),
                            ("MULTIMETER", "멀티미터"),
                            ("OSCILLOSCOPE", "오실로스코프"),
                            ("VISUAL", "육안검사"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="기구유형",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="제조사"
                    ),
                ),
                (
                    "model_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="모델번호"
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="일련번호"
                    ),
                ),
                (
                    "measurement_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="측정범위최소",
                    ),
                ),
                (
                    "measurement_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="측정범위최대",
                    ),
                ),
                (
                    "resolution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="분해능",
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="단위")),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="예: ±0.001mm",
                        max_digits=10,
                        null=True,
                        verbose_name="정밀도",
                    ),
                ),
                (
                    "calibration_cycle",
                    models.IntegerField(default=365, verbose_name="보정주기(일)"),
                ),
                (
                    "last_calibration_date",
                    models.DateField(blank=True, null=True, verbose_name="최종보정일"),
                ),
                (
                    "next_calibration_date",
                    models.DateField(blank=True, null=True, verbose_name="다음보정일"),
                ),
                (
                    "calibration_institution",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="보정기관"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "사용가능"),
                            ("CALIBRATION_DUE", "보정만료"),
                            ("MAINTENANCE", "정비중"),
                            ("SCRAPPED", "폐기"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="보관위치"
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="담당자"
                    ),
                ),
                (
                    "gage_rr_required",
                    models.BooleanField(default=True, verbose_name="Gage R&R 필수"),
                ),
                (
                    "gage_rr_last_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gage R&R 실시일"
                    ),
                ),
                (
                    "gage_rr_result",
                    models.CharField(
                        choices=[
                            ("PASS", "적합"),
                            ("FAIL", "부적합"),
                            ("PENDING", "미실시"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Gage R&R 결과",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "측정기구마스터",
                "verbose_name_plural": "측정기구마스터",
                "db_table": "measurement_instrument_master",
                "ordering": ["instrument_cd"],
                "indexes": [
                    models.Index(fields=["instrument_type"], name="ix_inst_type"),
                    models.Index(fields=["status"], name="ix_inst_status"),
                    models.Index(fields=["next_calibration_date"], name="ix_inst_cal"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeasurementSystemComponent",
            fields=[
                ("component_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "component_role",
                    models.CharField(
                        help_text="예: 주측정기, 보조측정기",
                        max_length=50,
                        verbose_name="구성역할",
                    ),
                ),
                ("seq", models.IntegerField(default=1, verbose_name="순번")),
                (
                    "ev_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Equipment Variation 기여도",
                        max_digits=5,
                        null=True,
                        verbose_name="EV 기여도(%)",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_components",
                        to="spc.measurementinstrumentmaster",
                        verbose_name="기구",
                    ),
                ),
            ],
            options={
                "verbose_name": "측정시스템구성",
                "verbose_name_plural": "측정시스템구성",
                "db_table": "measurement_system_component",
                "ordering": ["system", "seq"],
            },
        ),
        migrations.CreateModel(
            name="MeasurementSystemMaster",
            fields=[
                ("system_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "system_cd",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="시스템코드",
                    ),
                ),
                (
                    "system_nm",
                    models.CharField(max_length=200, verbose_name="시스템명"),
                ),
                (
                    "measurement_process",
                    models.TextField(
                        help_text="측정 절차 및 방법", verbose_name="측정프로세스"
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="온도범위최소(℃)",
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="온도범위최대(℃)",
                    ),
                ),
                (
                    "humidity_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="습도범위최소(%)"
                    ),
                ),
                (
                    "humidity_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="습도범위최대(%)"
                    ),
                ),
                (
                    "system_manager",
                    models.CharField(max_length=100, verbose_name="시스템담당자"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="설치위치")),
                (
                    "msa_method",
                    models.CharField(
                        choices=[
                            ("GAGE_RR", "Gage R&R"),
                            ("GAGE_LINEARITY", "Gage 선형성"),
                            ("GAGE_STABILITY", "Gage 안정성"),
                            ("GAGE_BIAS", "Gage 편향"),
                        ],
                        default="GAGE_RR",
                        max_length=20,
                        verbose_name="MSA 방법",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instruments",
                    models.ManyToManyField(
                        related_name="systems",
                        through="spc.MeasurementSystemComponent",
                        to="spc.measurementinstrumentmaster",
                        verbose_name="구성기구",
                    ),
                ),
            ],
            options={
                "verbose_name": "측정시스템마스터",
                "verbose_name_plural": "측정시스템마스터",
                "db_table": "measurement_system_master",
                "ordering": ["system_cd"],
            },
        ),
        migrations.AddField(
            model_name="measurementsystemcomponent",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="spc.measurementsystemmaster",
                verbose_name="시스템",
            ),
        ),
        migrations.CreateModel(
            name="QualityItemMaster",
            fields=[
                (
                    "quality_item_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "itm_id",
                    models.CharField(
                        db_index=True,
                        help_text="ERP 품목코드와 연계",
                        max_length=50,
                        unique=True,
                        verbose_name="품목코드",
                    ),
                ),
                ("itm_nm", models.CharField(max_length=200, verbose_name="품목명")),
                (
                    "itm_type",
                    models.CharField(
                        choices=[
                            ("RAW_MATERIAL", "원자재"),
                            ("WIP", "재공품"),
                            ("FINISHED_GOOD", "완제품"),
                            ("COMPONENT", "부품"),
                        ],
                        max_length=20,
                        verbose_name="품목유형",
                    ),
                ),
                (
                    "itm_family",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="품목패밀리"
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("A", "A급 - 핵심"),
                            ("B", "B급 - 일반"),
                            ("C", "C급 - 일반"),
                        ],
                        default="B",
                        max_length=20,
                        verbose_name="품질등급",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("FULL", "전수검사"),
                            ("SAMPLING", "샘플링검사"),
                            ("SKIP", "Skip 검사"),
                            ("NONE", "검사안함"),
                        ],
                        default="SAMPLING",
                        max_length=20,
                        verbose_name="검사유형",
                    ),
                ),
                (
                    "sampling_plan",
                    models.CharField(
                        blank=True,
                        help_text="예: MIL-STD-105E, AQL=1.5",
                        max_length=50,
                        null=True,
                        verbose_name="샘플링기준",
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(blank=True, null=True, verbose_name="샘플크기"),
                ),
                (
                    "sampling_frequency",
                    models.CharField(
                        blank=True,
                        help_text="예: 2시간말, 100개말",
                        max_length=50,
                        null=True,
                        verbose_name="샘플링빈도",
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="공급자코드"
                    ),
                ),
                (
                    "supplier_nm",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="공급자명"
                    ),
                ),
                (
                    "quality_manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="품질담당자"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "erp_sync_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP동기화시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "품질품목마스터",
                "verbose_name_plural": "품질품목마스터",
                "db_table": "quality_item_master",
                "ordering": ["itm_id"],
                "indexes": [
                    models.Index(fields=["itm_type"], name="ix_qitem_type"),
                    models.Index(fields=["itm_family"], name="ix_qitem_family"),
                    models.Index(fields=["quality_grade"], name="ix_qitem_grade"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityProcessMaster",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "process_cd",
                    models.CharField(
                        db_index=True,
                        help_text="MES 공정코드와 연계",
                        max_length=20,
                        unique=True,
                        verbose_name="공정코드",
                    ),
                ),
                ("process_nm", models.CharField(max_length=200, verbose_name="공정명")),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "수입검사"),
                            ("PROCESS", "공정검사"),
                            ("FINAL", "최종검사"),
                            ("OUTGOING", "출하검사"),
                        ],
                        max_length=20,
                        verbose_name="공정유형",
                    ),
                ),
                (
                    "workcenter_cd",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="작업장코드"
                    ),
                ),
                (
                    "workcenter_nm",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="작업장명"
                    ),
                ),
                (
                    "line_cd",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="라인코드"
                    ),
                ),
                (
                    "process_seq",
                    models.IntegerField(default=1, verbose_name="공정순서"),
                ),
                (
                    "total_characteristics",
                    models.IntegerField(default=0, verbose_name="관리특성수"),
                ),
                (
                    "process_manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="공정담당자"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mes_sync_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="MES동기화시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "품질공정마스터",
                "verbose_name_plural": "품질공정마스터",
                "db_table": "quality_process_master",
                "ordering": ["process_cd"],
                "indexes": [
                    models.Index(fields=["process_type"], name="ix_qproc_type"),
                    models.Index(fields=["workcenter_cd"], name="ix_qproc_wc"),
                    models.Index(fields=["line_cd"], name="ix_qproc_line"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityCharacteristicMaster",
            fields=[
                (
                    "characteristic_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "characteristic_cd",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="특성코드",
                    ),
                ),
                (
                    "characteristic_nm",
                    models.CharField(max_length=200, verbose_name="특성명"),
                ),
                (
                    "characteristic_type",
                    models.CharField(
                        choices=[
                            ("DIMENSION", "치수"),
                            ("WEIGHT", "중량"),
                            ("VOLTAGE", "전압"),
                            ("CURRENT", "전류"),
                            ("TEMPERATURE", "온도"),
                            ("PRESSURE", "압력"),
                            ("VISUAL", "외관"),
                            ("FUNCTIONAL", "기능"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="특성유형",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("CONTINUOUS", "연속형"),
                            ("DISCRETE", "이산형"),
                            ("ATTRIBUTE", "속성형"),
                        ],
                        default="CONTINUOUS",
                        max_length=20,
                        verbose_name="데이터유형",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="예: mm, g, V, A, ℃",
                        max_length=20,
                        verbose_name="측정단위",
                    ),
                ),
                (
                    "lsl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="하한규격(LSL)",
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="목표치(Target)",
                    ),
                ),
                (
                    "usl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="상한규격(USL)",
                    ),
                ),
                (
                    "cpk_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.33"),
                        max_digits=5,
                        verbose_name="Cpk목표",
                    ),
                ),
                (
                    "cpk_minimum",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        verbose_name="Cpk최소",
                    ),
                ),
                (
                    "control_chart_type",
                    models.CharField(
                        choices=[
                            ("XBAR_R", "Xbar-R 관리도"),
                            ("XBAR_S", "Xbar-S 관리도"),
                            ("I_MR", "I-MR 관리도"),
                            ("P", "P 관리도"),
                            ("NP", "NP 관리도"),
                            ("C", "C 관리도"),
                            ("U", "U 관리도"),
                        ],
                        default="XBAR_R",
                        max_length=20,
                        verbose_name="관리도유형",
                    ),
                ),
                (
                    "subgroup_size",
                    models.IntegerField(
                        default=5,
                        help_text="Xbar-R: 일반적으로 3-5, I-MR: 1",
                        verbose_name="부분군크기",
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="측정방법"
                    ),
                ),
                (
                    "measurement_location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="측정위치"
                    ),
                ),
                (
                    "quality_manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="품질담당자"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="spc.qualityitemmaster",
                        verbose_name="품목",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="spc.qualityprocessmaster",
                        verbose_name="공정",
                    ),
                ),
            ],
            options={
                "verbose_name": "품질특성마스터",
                "verbose_name_plural": "품질특성마스터",
                "db_table": "quality_characteristic_master",
                "ordering": ["characteristic_cd"],
            },
        ),
        migrations.CreateModel(
            name="QualitySyncLog",
            fields=[
                ("sync_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("ITEM", "품목마스터"),
                            ("PROCESS", "공정마스터"),
                            ("CHARACTERISTIC", "특성마스터"),
                            ("INSTRUMENT", "측정기구"),
                            ("STANDARD", "검사기준"),
                            ("MEASUREMENT", "측정데이터"),
                        ],
                        max_length=50,
                        verbose_name="동기화유형",
                    ),
                ),
                (
                    "sync_source",
                    models.CharField(
                        choices=[
                            ("ERP", "ERP"),
                            ("MES", "MES"),
                            ("LEGACY", "레거시"),
                            ("MANUAL", "수동입력"),
                        ],
                        max_length=20,
                        verbose_name="데이터원천",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                            ("PARTIAL", "부분성공"),
                        ],
                        max_length=20,
                        verbose_name="동기화상태",
                    ),
                ),
                (
                    "records_total",
                    models.IntegerField(default=0, verbose_name="총건수"),
                ),
                (
                    "records_success",
                    models.IntegerField(default=0, verbose_name="성공건수"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="실패건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류메시지"),
                ),
                (
                    "sync_details",
                    models.JSONField(
                        blank=True,
                        help_text="성공/실패 레코드 상세 정보",
                        null=True,
                        verbose_name="동기화상세",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="소스시스템"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="소스파일"
                    ),
                ),
                ("sync_start_ts", models.DateTimeField(verbose_name="동기화시작시각")),
                (
                    "sync_end_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="동기화종료시각"
                    ),
                ),
                (
                    "sync_ts",
                    models.DateTimeField(auto_now_add=True, verbose_name="동기화시각"),
                ),
            ],
            options={
                "verbose_name": "품질데이터동기화로그",
                "verbose_name_plural": "품질데이터동기화로그",
                "db_table": "quality_sync_log",
                "ordering": ["-sync_ts"],
                "indexes": [
                    models.Index(
                        fields=["sync_type", "-sync_ts"], name="ix_qsync_type_ts"
                    ),
                    models.Index(
                        fields=["sync_source", "-sync_ts"], name="ix_qsync_src_ts"
                    ),
                    models.Index(fields=["sync_status"], name="ix_qsync_status"),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="measurementsystemcomponent",
            unique_together={("system", "instrument")},
        ),
        migrations.CreateModel(
            name="InspectionStandardMaster",
            fields=[
                ("standard_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "standard_cd",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="기준코드",
                    ),
                ),
                (
                    "standard_nm",
                    models.CharField(max_length=200, verbose_name="기준명"),
                ),
                (
                    "standard_type",
                    models.CharField(
                        choices=[
                            ("INSPECTION", "검사기준"),
                            ("TEST", "시험기준"),
                            ("SPECIFICATION", "규격기준"),
                            ("ACCEPTANCE", "합격판정기준"),
                        ],
                        max_length=20,
                        verbose_name="기준유형",
                    ),
                ),
                (
                    "inspection_condition",
                    models.TextField(
                        blank=True,
                        help_text="온도, 습도, 전압 등 검사 환경 조건",
                        null=True,
                        verbose_name="검사조건",
                    ),
                ),
                ("acceptance_criteria", models.TextField(verbose_name="합격판정기준")),
                (
                    "rejection_criteria",
                    models.TextField(
                        blank=True, null=True, verbose_name="불합격판정기준"
                    ),
                ),
                (
                    "sampling_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="샘플링방법"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(blank=True, null=True, verbose_name="샘플크기"),
                ),
                (
                    "aql",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="AQL(%)",
                    ),
                ),
                (
                    "test_method",
                    models.TextField(blank=True, null=True, verbose_name="시험방법"),
                ),
                (
                    "test_equipment",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="시험장비"
                    ),
                ),
                (
                    "reference_doc",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="참조문서"
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="개정번호"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="시행일자"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "characteristic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="spc.qualitycharacteristicmaster",
                        verbose_name="특성",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="spc.qualityitemmaster",
                        verbose_name="품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사기준마스터",
                "verbose_name_plural": "검사기준마스터",
                "db_table": "inspection_standard_master",
                "ordering": ["standard_cd"],
                "indexes": [
                    models.Index(
                        fields=["item", "characteristic"], name="ix_std_item_char"
                    ),
                    models.Index(fields=["standard_type"], name="ix_std_type"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qualitycharacteristicmaster",
            index=models.Index(fields=["item", "process"], name="ix_qchar_item_proc"),
        ),
        migrations.AddIndex(
            model_name="qualitycharacteristicmaster",
            index=models.Index(fields=["characteristic_type"], name="ix_qchar_type"),
        ),
    ]
