# Generated by Django 6.0.1 on 2026-01-12 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spc", "0002_measurementinstrumentmaster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSite",
            fields=[
                ("site_id", models.AutoField(primary_key=True, serialize=False)),
                ("site_name", models.CharField(max_length=200, unique=True)),
                ("timezone", models.CharField(default="Asia/Seoul", max_length=50)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "org_site",
                "ordering": ["site_name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationDepartment",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100)),
                ("owner_user_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "org_dept",
                "ordering": ["site", "dept_name"],
            },
        ),
        migrations.CreateModel(
            name="InspectionPlanNew",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=200)),
                ("rev_no", models.CharField(default="1.0", max_length=20)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("ALL", "전수 검사"),
                            ("SAMPLING", "샘플링 검사"),
                            ("SENSORY", "관능 검사"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency_rule",
                    models.CharField(
                        choices=[
                            ("EACH_LOT", "LOT별"),
                            ("EACH_SHIFT", "교대별"),
                            ("DAILY", "일일"),
                            ("N_PCS", "N개마다"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "활성"),
                            ("INACTIVE", "비활성"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_plans_v2",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_plan_v2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GageMaster",
            fields=[
                ("gage_id", models.AutoField(primary_key=True, serialize=False)),
                ("gage_name", models.CharField(max_length=200)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("calibration_due_dt", models.DateTimeField()),
                ("calibration_interval_days", models.IntegerField(default=365)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gages",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "gage_master",
                "ordering": ["gage_name"],
            },
        ),
        migrations.CreateModel(
            name="DocFile",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=100)),
                (
                    "uri",
                    models.CharField(help_text="파일 경로 또는 URL", max_length=500),
                ),
                (
                    "linked_type",
                    models.CharField(help_text="연계된 모델 타입", max_length=50),
                ),
                ("linked_id", models.IntegerField(help_text="연계된 모델 ID")),
                ("uploaded_by", models.IntegerField()),
                ("uploaded_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_files",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "doc_file",
                "ordering": ["-uploaded_dt"],
            },
        ),
        migrations.CreateModel(
            name="ChangeControl",
            fields=[
                ("chg_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("PLAN", "검사 계획"),
                            ("SPEC", "검사 규격"),
                            ("PROCESS", "공정"),
                            ("WORKINSTR", "작업 표준"),
                            ("DOC", "문서"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.IntegerField(help_text="변경 대상 ID")),
                ("from_rev", models.CharField(help_text="이전 리비전", max_length=20)),
                ("to_rev", models.CharField(help_text="새 리비전", max_length=20)),
                ("reason", models.TextField(help_text="변경 사유")),
                ("requested_by", models.IntegerField(help_text="요청자 ID")),
                ("approved_by", models.IntegerField(blank=True, null=True)),
                ("approved_dt", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("changes_summary", models.TextField(help_text="변경 요약")),
                (
                    "impact_analysis",
                    models.TextField(blank=True, help_text="영향 평가"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_controls",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "change_control",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessFlow",
            fields=[
                ("flow_id", models.AutoField(primary_key=True, serialize=False)),
                ("flow_name", models.CharField(max_length=200)),
                ("rev_no", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "활성"),
                            ("OBSOLETE", "폐기"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_flows",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "process_flow",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LotProduction",
            fields=[
                ("lot_id", models.AutoField(primary_key=True, serialize=False)),
                ("lot_no", models.CharField(max_length=50, unique=True)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=15)),
                ("start_dt", models.DateTimeField()),
                ("end_dt", models.DateTimeField(blank=True, null=True)),
                ("shift", models.CharField(max_length=20)),
                ("operator_id", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="IN_PROGRESS", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_lots",
                        to="spc.organizationsite",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_lots",
                        to="spc.processflow",
                    ),
                ),
            ],
            options={
                "db_table": "lot_production",
                "ordering": ["-start_dt"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                ("step_id", models.AutoField(primary_key=True, serialize=False)),
                ("seq_no", models.IntegerField(help_text="순서")),
                ("step_name", models.CharField(max_length=100)),
                ("workcenter", models.CharField(blank=True, max_length=100)),
                ("machine_group", models.CharField(blank=True, max_length=100)),
                (
                    "is_inspection_point",
                    models.BooleanField(default=False, help_text="검사 지점 여부"),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="spc.processflow",
                    ),
                ),
            ],
            options={
                "db_table": "process_step",
                "ordering": ["flow", "seq_no"],
                "unique_together": {("flow", "seq_no")},
            },
        ),
        migrations.CreateModel(
            name="InspectionRun",
            fields=[
                ("run_id", models.AutoField(primary_key=True, serialize=False)),
                ("run_dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("inspector_id", models.IntegerField(help_text="검사자 ID")),
                ("sample_n", models.IntegerField(help_text="샘플 번호")),
                (
                    "environment",
                    models.JSONField(
                        blank=True, help_text="온습도 등 환경 정보", null=True
                    ),
                ),
                (
                    "overall_judgement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "합격"),
                            ("FAIL", "불합격"),
                            ("HOLD", "보류"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ai_summary_id",
                    models.IntegerField(
                        blank=True, help_text="AI 요약 연결", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="spc.inspectionplannew",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_runs",
                        to="spc.lotproduction",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_runs",
                        to="spc.organizationsite",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_runs",
                        to="spc.processstep",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_run",
                "ordering": ["-run_dt"],
            },
        ),
        migrations.AddField(
            model_name="inspectionplannew",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_plans_v2",
                to="spc.processstep",
            ),
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(max_length=200)),
                ("spec_version", models.CharField(default="A0", max_length=20)),
                (
                    "uom",
                    models.CharField(help_text="단위 (mm, kg, etc)", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_items",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "product_item",
                "ordering": ["item_code"],
                "unique_together": {("site", "item_code")},
            },
        ),
        migrations.AddField(
            model_name="lotproduction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_lots",
                to="spc.productitem",
            ),
        ),
        migrations.AddField(
            model_name="inspectionplannew",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_plans_v2",
                to="spc.productitem",
            ),
        ),
        migrations.CreateModel(
            name="QAProcess",
            fields=[
                ("qa_proc_id", models.AutoField(primary_key=True, serialize=False)),
                ("proc_name", models.CharField(max_length=200)),
                ("rev_no", models.CharField(default="1.0", max_length=20)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_processes",
                        to="spc.organizationdepartment",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_processes",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "qa_process",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QAAssessment",
            fields=[
                ("assess_id", models.AutoField(primary_key=True, serialize=False)),
                ("assess_dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("assessor_id", models.IntegerField(help_text="진단자 ID")),
                ("scope", models.TextField(help_text="진단 범위")),
                (
                    "overall_level",
                    models.CharField(
                        help_text="전체 등급 (예: Level 1~5)", max_length=20
                    ),
                ),
                ("ai_summary_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_assessments",
                        to="spc.organizationsite",
                    ),
                ),
                (
                    "qa_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="spc.qaprocess",
                    ),
                ),
            ],
            options={
                "db_table": "qa_assessment",
                "ordering": ["-assess_dt"],
            },
        ),
        migrations.CreateModel(
            name="QARequirement",
            fields=[
                ("req_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "req_type",
                    models.CharField(
                        choices=[
                            ("ISO", "ISO 표준"),
                            ("IATF", "IATF 표준"),
                            ("INHOUSE", "사내 규정"),
                            ("CUSTOMER", "고객 요구사항"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clause", models.CharField(help_text="조항 번호", max_length=100)),
                ("req_text", models.TextField(help_text="요구사항 내용")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "매우 중요"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence_needed", models.BooleanField(default=True)),
                (
                    "control_method",
                    models.CharField(
                        choices=[
                            ("DOC", "문서"),
                            ("RECORD", "기록"),
                            ("SYSTEM", "시스템"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="spc.qaprocess",
                    ),
                ),
            ],
            options={
                "db_table": "qa_requirement",
                "ordering": ["qa_process", "clause"],
            },
        ),
        migrations.CreateModel(
            name="QAGapFinding",
            fields=[
                ("finding_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("MISSING", "미비"),
                            ("UPDATE", "수정 필요"),
                            ("IMPROVE", "개선 권고"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        max_length=20,
                    ),
                ),
                ("as_is", models.TextField(help_text="현재 상태")),
                ("to_be", models.TextField(help_text="목표 상태")),
                ("evidence", models.TextField(blank=True, help_text="증거 자료")),
                ("due_dt", models.DateTimeField(help_text="목표 일정")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "미해결"),
                            ("IN_PROGRESS", "진행중"),
                            ("DONE", "완료"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("owner_user_id", models.IntegerField(help_text="담당자 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="spc.qaassessment",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="spc.qarequirement",
                    ),
                ),
            ],
            options={
                "db_table": "qa_gap_finding",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCCharacteristic",
            fields=[
                ("char_id", models.AutoField(primary_key=True, serialize=False)),
                ("char_name", models.CharField(max_length=100)),
                (
                    "char_type",
                    models.CharField(
                        choices=[
                            ("DIM", "치수 특성"),
                            ("ATTR", "속성 특성"),
                            ("SENSORY", "관능 특성"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("target", models.FloatField(blank=True, null=True)),
                ("lsl", models.FloatField(blank=True, help_text="하한규격", null=True)),
                ("usl", models.FloatField(blank=True, help_text="상한규격", null=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[("C", "Critical"), ("A", "A"), ("B", "B")],
                        default="B",
                        max_length=10,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, help_text="공통 템플릿 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="spc.productitem",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="spc.organizationsite",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="spc.processstep",
                    ),
                ),
            ],
            options={
                "db_table": "qc_characteristic",
                "ordering": ["item", "step", "char_name"],
            },
        ),
        migrations.CreateModel(
            name="InspectionSpec",
            fields=[
                ("spec_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "judge_method",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "수치 판정"),
                            ("ENUM", "열거 판정"),
                            ("TEXT", "텍스트 판정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numeric_lsl", models.FloatField(blank=True, null=True)),
                ("numeric_target", models.FloatField(blank=True, null=True)),
                ("numeric_usl", models.FloatField(blank=True, null=True)),
                (
                    "enum_values",
                    models.JSONField(blank=True, help_text="허용값 리스트", null=True),
                ),
                ("measurement_method", models.TextField(blank=True)),
                ("gage_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="spc.inspectionplannew",
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="spc.qccharacteristic",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_spec",
                "ordering": ["plan", "char"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("sample_no", models.IntegerField()),
                ("value_num", models.FloatField(blank=True, null=True)),
                ("value_text", models.CharField(blank=True, max_length=500)),
                ("value_enum", models.CharField(blank=True, max_length=100)),
                ("is_out_of_spec", models.BooleanField(default=False)),
                ("defect_code_id", models.IntegerField(blank=True, null=True)),
                ("remark", models.TextField(blank=True)),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="spc.inspectionrun",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="spc.inspectionspec",
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="spc.qccharacteristic",
                    ),
                ),
            ],
            options={
                "db_table": "inspection_result",
                "ordering": ["run", "sample_no"],
            },
        ),
        migrations.CreateModel(
            name="QCostCategory",
            fields=[
                ("qcat_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "lvl1",
                    models.CharField(
                        choices=[
                            ("PREVENTION", "예방비용"),
                            ("APPRAISAL", "평가비용"),
                            ("INTERNAL_FAILURE", "내부 실패비용"),
                            ("EXTERNAL_FAILURE", "외부 실패비용"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lvl2", models.CharField(blank=True, max_length=100)),
                ("lvl3", models.CharField(blank=True, max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcost_categories",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "qcost_category",
                "ordering": ["lvl1", "lvl2", "lvl3"],
                "unique_together": {("site", "code")},
            },
        ),
        migrations.CreateModel(
            name="QCostItemMaster",
            fields=[
                ("qitem_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=200)),
                (
                    "unit_cost_rule",
                    models.CharField(
                        choices=[
                            ("FIXED", "고정단가"),
                            ("RATE", "율적용"),
                            ("MANUAL", "수동입력"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("gl_account", models.CharField(blank=True, max_length=50)),
                (
                    "copq_flag",
                    models.BooleanField(default=False, help_text="COPQ 대상 여부"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="spc.qcostcategory",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.organizationdepartment",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcost_items",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "qcost_item_master",
                "ordering": ["category", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="SamplingRule",
            fields=[
                ("sample_rule_id", models.AutoField(primary_key=True, serialize=False)),
                ("rule_name", models.CharField(max_length=100)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("ISO2859", "ISO 2859-1"),
                            ("ANSI_Z1_4", "ANSI/ASQ Z1.4"),
                            ("INHOUSE", "사내 규격"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aql", models.FloatField(help_text="Acceptable Quality Level")),
                ("inspection_level", models.CharField(default="II", max_length=20)),
                ("lot_size_min", models.IntegerField(blank=True, null=True)),
                ("lot_size_max", models.IntegerField(blank=True, null=True)),
                ("sample_size", models.IntegerField(help_text="샘플 크기")),
                ("accept_num", models.IntegerField(help_text="합격 판정 수")),
                ("reject_num", models.IntegerField(help_text="불합격 판정 수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sampling_rules",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "sampling_rule",
                "ordering": ["rule_name"],
            },
        ),
        migrations.AddField(
            model_name="inspectionplannew",
            name="sampling_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspection_plans_v2",
                to="spc.samplingrule",
            ),
        ),
        migrations.CreateModel(
            name="SPCChartDefinition",
            fields=[
                ("chart_def_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("XBAR_R", "X-bar & R Chart"),
                            ("XBAR_S", "X-bar & S Chart"),
                            ("I_MR", "Individual & Moving Range Chart"),
                            ("P", "p-Chart"),
                            ("NP", "np-Chart"),
                            ("C", "c-Chart"),
                            ("U", "u-Chart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calc_method",
                    models.CharField(
                        choices=[("STANDARD", "표준 방법"), ("ROBUST", "Robust 방법")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("subgroup_size", models.IntegerField(default=5)),
                (
                    "rule_set",
                    models.JSONField(default=dict, help_text="적용할 WECO Rules 등"),
                ),
                ("baseline_from_dt", models.DateTimeField(help_text="기준 기간 시작")),
                ("baseline_to_dt", models.DateTimeField(help_text="기준 기간 종료")),
                (
                    "ucl",
                    models.FloatField(blank=True, help_text="상한관리선", null=True),
                ),
                ("cl", models.FloatField(blank=True, help_text="중심선", null=True)),
                (
                    "lcl",
                    models.FloatField(blank=True, help_text="하한관리선", null=True),
                ),
                ("cp", models.FloatField(blank=True, null=True)),
                ("cpk", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spc_charts",
                        to="spc.qccharacteristic",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spc_charts",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "spc_chart_def",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SPCChartPoint",
            fields=[
                ("point_id", models.AutoField(primary_key=True, serialize=False)),
                ("point_dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("n", models.IntegerField(help_text="샘플 수")),
                ("xbar", models.FloatField(blank=True, help_text="평균", null=True)),
                ("r", models.FloatField(blank=True, help_text="범위", null=True)),
                ("s", models.FloatField(blank=True, help_text="표준편차", null=True)),
                ("mr", models.FloatField(blank=True, help_text="이동 범위", null=True)),
                ("p", models.FloatField(blank=True, help_text="불합격률", null=True)),
                ("np", models.FloatField(blank=True, help_text="불합격수", null=True)),
                ("c", models.FloatField(blank=True, help_text="결점수", null=True)),
                (
                    "u",
                    models.FloatField(blank=True, help_text="단위당 결점수", null=True),
                ),
                ("ucl", models.FloatField(blank=True, null=True)),
                ("cl", models.FloatField(blank=True, null=True)),
                ("lcl", models.FloatField(blank=True, null=True)),
                ("cp", models.FloatField(blank=True, null=True)),
                ("cpk", models.FloatField(blank=True, null=True)),
                ("is_violation", models.BooleanField(default=False)),
                (
                    "violation_codes",
                    models.JSONField(default=list, help_text="위반한 규칙 리스트"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="spc.spcchartdefinition",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spc_points",
                        to="spc.inspectionrun",
                    ),
                ),
            ],
            options={
                "db_table": "spc_chart_point",
                "ordering": ["-point_dt"],
            },
        ),
        migrations.CreateModel(
            name="SPCEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_dt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("OOS", "Out of Spec"),
                            ("RULE_VIOLATION", "Rule Violation"),
                            ("SHIFT", "Shift Change"),
                            ("TREND", "Trend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "미해결"),
                            ("ACK", "확인됨"),
                            ("INVESTIGATING", "조사중"),
                            ("CLOSED", "종료"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("owner_user_id", models.IntegerField(help_text="담당자 ID")),
                ("ai_rootcause_id", models.IntegerField(blank=True, null=True)),
                (
                    "ai_analysis",
                    models.JSONField(blank=True, help_text="AI 분석 결과", null=True),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.IntegerField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="spc.spcchartdefinition",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="spc.spcchartpoint",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spc_events",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "spc_event",
                "ordering": ["-event_dt"],
            },
        ),
        migrations.CreateModel(
            name="DefectCode",
            fields=[
                ("defect_code_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("severity", models.IntegerField(help_text="1~10, 10이 가장 심각")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_codes",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "defect_code",
                "ordering": ["category", "code"],
                "unique_together": {("site", "code")},
            },
        ),
        migrations.CreateModel(
            name="COPQSummary",
            fields=[
                ("copq_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "period_yyyymm",
                    models.CharField(help_text="집계 기간 (YYYY-MM)", max_length=7),
                ),
                (
                    "total_qcost",
                    models.DecimalField(
                        decimal_places=2, help_text="총 품질비용", max_digits=18
                    ),
                ),
                (
                    "total_copq",
                    models.DecimalField(
                        decimal_places=2, help_text="총 COPQ", max_digits=18
                    ),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("copq_rate", models.FloatField(help_text="COPQ율 (COPQ/매출액)")),
                (
                    "by_category",
                    models.JSONField(default=dict, help_text="카테고리별 집계"),
                ),
                ("by_dept", models.JSONField(default=dict, help_text="부서별 집계")),
                (
                    "top_drivers",
                    models.JSONField(default=list, help_text="주요 원인 항목"),
                ),
                ("ai_insight_id", models.IntegerField(blank=True, null=True)),
                ("ai_recommendation", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copq_summaries",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "copq_summary",
                "ordering": ["-period_yyyymm"],
                "unique_together": {("site", "period_yyyymm")},
            },
        ),
        migrations.CreateModel(
            name="CAPACase",
            fields=[
                ("capa_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SPC_EVENT", "SPC 이벤트"),
                            ("INSPECTION_FAIL", "검사 불합격"),
                            ("QA_FINDING", "QA GAP 분석"),
                            ("CUSTOMER_CLAIM", "고객 클레임"),
                            ("INTERNAL_AUDIT", "내부 감사"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.IntegerField(help_text="원본 이벤트/문제 ID")),
                ("problem_statement", models.TextField(help_text="문제 정의")),
                ("containment_action", models.TextField(help_text="잠시 조치")),
                ("root_cause", models.TextField(help_text="근본 원인")),
                ("corrective_action", models.TextField(help_text="시정 조치")),
                ("preventive_action", models.TextField(help_text="예방 조치")),
                ("owner_user_id", models.IntegerField(help_text="담당자 ID")),
                ("due_dt", models.DateTimeField(help_text="목표 완료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "미해결"),
                            ("IN_PROGRESS", "진행중"),
                            ("VERIFICATION", "효과 확인중"),
                            ("CLOSED", "종료"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("effectiveness_check_dt", models.DateTimeField(blank=True, null=True)),
                ("effectiveness_verified", models.BooleanField(blank=True, null=True)),
                (
                    "ai_recommendation",
                    models.JSONField(blank=True, help_text="AI 추천 조치", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capa_cases",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "capa_case",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "status"], name="capa_case_site_id_145a2e_idx"
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="capa_case_source__8eff1b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIOutput",
            fields=[
                ("ai_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("CHECKLIST", "체크리스트 생성"),
                            ("CRITERIA", "판정 기준 생성"),
                            ("REPORT", "보고서 생성"),
                            ("ROOTCAUSE", "근본 원인 분석"),
                            ("QC_PLAN", "QC 계획 생성"),
                            ("RECOMMENDATION", "개선 추천"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_hash", models.CharField(max_length=64, unique=True)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=20)),
                ("output_json", models.JSONField()),
                ("confidence", models.FloatField(help_text="신뢰도 (0~1)")),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_outputs",
                        to="spc.organizationsite",
                    ),
                ),
            ],
            options={
                "db_table": "ai_output",
                "ordering": ["-created_dt"],
                "indexes": [
                    models.Index(
                        fields=["site", "use_case"], name="ai_output_site_id_8f7f44_idx"
                    ),
                    models.Index(
                        fields=["input_hash"], name="ai_output_input_h_bfafb6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QCostEntry",
            fields=[
                ("entry_id", models.AutoField(primary_key=True, serialize=False)),
                ("occur_dt", models.DateTimeField(help_text="비용 발생일")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KRW", "원화"),
                            ("USD", "달러"),
                            ("EUR", "유로"),
                            ("JPY", "엔"),
                        ],
                        default="KRW",
                        max_length=10,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="수량",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "lot_id",
                    models.IntegerField(
                        blank=True, help_text="생산 LOT 연계", null=True
                    ),
                ),
                (
                    "run_id",
                    models.IntegerField(
                        blank=True, help_text="검사 실행 연계", null=True
                    ),
                ),
                (
                    "spc_event_id",
                    models.IntegerField(
                        blank=True, help_text="SPC 이벤트 연계", null=True
                    ),
                ),
                (
                    "capa_id",
                    models.IntegerField(blank=True, help_text="CAPA 연계", null=True),
                ),
                (
                    "vendor_id",
                    models.IntegerField(blank=True, help_text="협력사 연계", null=True),
                ),
                ("evidence_file_id", models.IntegerField(blank=True, null=True)),
                ("memo", models.TextField(blank=True)),
                (
                    "ai_classification",
                    models.JSONField(
                        blank=True,
                        help_text="AI 분류 결과: {category_id, confidence, reason}",
                        null=True,
                    ),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True, help_text="AI 분류 신뢰도 (0~1)", null=True
                    ),
                ),
                ("entered_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spc.organizationdepartment",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcost_entries",
                        to="spc.organizationsite",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="spc.qcostitemmaster",
                    ),
                ),
            ],
            options={
                "db_table": "qcost_entry",
                "ordering": ["-occur_dt"],
                "indexes": [
                    models.Index(
                        fields=["site", "occur_dt"],
                        name="qcost_entry_site_id_d56b1d_idx",
                    ),
                    models.Index(
                        fields=["item"], name="qcost_entry_item_id_28790f_idx"
                    ),
                    models.Index(
                        fields=["dept"], name="qcost_entry_dept_id_51fb35_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="spcchartpoint",
            index=models.Index(
                fields=["chart_def", "point_dt"], name="spc_chart_p_chart_d_f1fdca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spcevent",
            index=models.Index(
                fields=["site", "status"], name="spc_event_site_id_c1b9ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spcevent",
            index=models.Index(
                fields=["event_dt"], name="spc_event_event_d_01aec4_idx"
            ),
        ),
    ]
