# Generated by Django 4.2.7 on 2026-01-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SamplingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(help_text="규칙 ID", max_length=50, unique=True),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("MIL-STD-105E", "MIL-STD-105E"),
                            ("ISO-2859-1", "ISO 2859-1"),
                            ("ISO-2859-2", "ISO 2859-2"),
                            ("ANSI-ASQ-Z1.4", "ANSI/ASQ Z1.4"),
                        ],
                        help_text="표준",
                        max_length=20,
                    ),
                ),
                ("aql", models.FloatField(help_text="AQL 수준")),
                ("lot_size_from", models.IntegerField(help_text="로트 크기 시작")),
                ("lot_size_to", models.IntegerField(help_text="로트 크기 종료")),
                ("sample_size", models.IntegerField(help_text="표본 크기")),
                ("accept_limit", models.IntegerField(help_text="합격 판정 개수")),
                ("reject_limit", models.IntegerField(help_text="불합격 판정 개수")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sampling Rule",
                "verbose_name_plural": "Sampling Rules",
                "db_table": "sampling_rule",
                "ordering": ["standard", "lot_size_from"],
            },
        ),
        migrations.CreateModel(
            name="SpcChartDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_def_id",
                    models.CharField(
                        help_text="관리도 정의 ID", max_length=50, unique=True
                    ),
                ),
                (
                    "parameter_id",
                    models.CharField(help_text="파라미터 ID", max_length=50),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("XBAR_R", "X-bar R 관리도"),
                            ("XBAR_S", "X-bar S 관리도"),
                            ("I_MR", "I-MR 관리도"),
                            ("P", "P 관리도"),
                            ("NP", "NP 관리도"),
                            ("U", "U 관리도"),
                            ("C", "C 관리도"),
                        ],
                        help_text="관리도 종류",
                        max_length=10,
                    ),
                ),
                ("sample_size", models.IntegerField(help_text="표본 크기 (n)")),
                (
                    "ucl",
                    models.FloatField(blank=True, help_text="상한 (UCL)", null=True),
                ),
                (
                    "cl",
                    models.FloatField(blank=True, help_text="중심선 (CL)", null=True),
                ),
                (
                    "lcl",
                    models.FloatField(blank=True, help_text="하한 (LCL)", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SPC Chart Definition",
                "verbose_name_plural": "SPC Chart Definitions",
                "db_table": "spc_chart_definition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpcPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_id",
                    models.CharField(help_text="포인트 ID", max_length=50, unique=True),
                ),
                ("timestamp", models.DateTimeField(help_text="측정일시")),
                ("sample_id", models.CharField(help_text="표본 ID", max_length=50)),
                ("value", models.FloatField(help_text="측정값")),
                (
                    "mean",
                    models.FloatField(blank=True, help_text="평균 (Xbar)", null=True),
                ),
                (
                    "range_val",
                    models.FloatField(blank=True, help_text="범위 (R)", null=True),
                ),
                (
                    "std_dev",
                    models.FloatField(blank=True, help_text="표준편차 (S)", null=True),
                ),
                (
                    "violated_rules",
                    models.JSONField(
                        blank=True, help_text="위반 규칙 목록 (JSON)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart_def",
                    models.ForeignKey(
                        help_text="관리도 정의",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="spc.spcchartdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "SPC Point",
                "verbose_name_plural": "SPC Points",
                "db_table": "spc_point",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SpcEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(help_text="이벤트 ID", max_length=50, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("OOS", "규격 이탈"),
                            ("RULE_1", "Rule 1: 1점이 3σ 벗어남"),
                            ("RULE_2", "Rule 2: 연속 3점 중 2점이 2σ 벗어남"),
                            ("RULE_3", "Rule 3: 연속 5점 중 4점이 1σ 벗어남"),
                            ("RULE_4", "Rule 4: 연속 8점이 중심선同一편"),
                            ("RULE_5", "Rule 5: 연속 6점이 단조 증가/감소"),
                            ("RULE_6", "Rule 6: 연속 14점이 교차"),
                            ("RULE_7", "Rule 7: 연속 15점이 1σ 내"),
                            ("RULE_8", "Rule 8: 연속 8점이 1σ 밖"),
                            ("TREND", "추세 이상"),
                        ],
                        help_text="이벤트 유형",
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(help_text="발생일시")),
                ("description", models.TextField(help_text="설명")),
                ("severity", models.IntegerField(help_text="심각도 (1-5)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="상태",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, help_text="담당자", max_length=50),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="해결일시", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart_def",
                    models.ForeignKey(
                        help_text="관리도 정의",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="spc.spcchartdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "SPC Event",
                "verbose_name_plural": "SPC Events",
                "db_table": "spc_event",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
