# Generated by Django 4.2.7 on 2026-01-16 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="시스템명")),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("ERP", "ERP"),
                            ("MES", "MES"),
                            ("PLM", "PLM"),
                            ("WMS", "WMS"),
                            ("QMS", "QMS"),
                        ],
                        max_length=20,
                        verbose_name="시스템 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "endpoint_url",
                    models.URLField(max_length=500, verbose_name="API Endpoint URL"),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("API_KEY", "API Key"),
                            ("OAUTH", "OAuth 2.0"),
                            ("BASIC_AUTH", "Basic Auth"),
                            ("BEARER_TOKEN", "Bearer Token"),
                        ],
                        max_length=20,
                        verbose_name="인증 방식",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Key"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="사용자명"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="비밀번호"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Access Token"
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Refresh Token"
                    ),
                ),
                (
                    "sync_frequency_minutes",
                    models.IntegerField(default=60, verbose_name="동기화 주기(분)"),
                ),
                (
                    "auto_sync",
                    models.BooleanField(default=True, verbose_name="자동 동기화"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "next_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 동기화"
                    ),
                ),
                (
                    "data_types",
                    models.JSONField(
                        default=list,
                        help_text='예: ["생산주문", "자재정보", "BOM", "작업지시"]',
                        verbose_name="데이터 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "연결됨"),
                            ("DISCONNECTED", "연결안됨"),
                            ("ERROR", "에러"),
                            ("TESTING", "테스트중"),
                        ],
                        default="DISCONNECTED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="마지막 에러"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "ERP 연계",
                "verbose_name_plural": "ERP 연계",
                "db_table": "erp_integrations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManualQualityInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="기록 번호"
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "입고 검사"),
                            ("PROCESS", "공정 검사"),
                            ("FINAL", "최종 검사"),
                            ("OUTGOING", "출하 검사"),
                        ],
                        max_length=20,
                        verbose_name="검사 유형",
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일")),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="제품 코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="배치 번호"
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="LOT 번호"
                    ),
                ),
                ("sample_size", models.IntegerField(verbose_name="표본 수")),
                (
                    "defect_count",
                    models.IntegerField(default=0, verbose_name="불량 수"),
                ),
                ("defect_rate", models.FloatField(default=0, verbose_name="불량률(%)")),
                (
                    "characteristics",
                    models.JSONField(
                        default=list,
                        help_text='예: [{"name": "길이", "target": 100, "tolerance": 0.5, "measured": 100.1, "status": "OK"}]',
                        verbose_name="특성별 검사 결과",
                    ),
                ),
                (
                    "defect_details",
                    models.JSONField(
                        default=list,
                        help_text='예: [{"type": "긁힘", "count": 5, "description": "표면 긁힘"}]',
                        verbose_name="불량 상세",
                    ),
                ),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="승인일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "attachments",
                    models.JSONField(default=list, verbose_name="첨부파일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검사자",
                    ),
                ),
            ],
            options={
                "verbose_name": "자체 입력",
                "verbose_name_plural": "자체 입력",
                "db_table": "manual_quality_inputs",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="동기화 ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "전체"),
                            ("INCREMENTAL", "증분"),
                            ("MANUAL", "수동"),
                        ],
                        max_length=20,
                        verbose_name="동기화 유형",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시간"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="소요 시간(초)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                            ("IN_PROGRESS", "진행중"),
                            ("PARTIAL", "부분 성공"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="처리 건수"),
                ),
                (
                    "records_success",
                    models.IntegerField(default=0, verbose_name="성공 건수"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="실패 건수"),
                ),
                (
                    "data_types",
                    models.JSONField(default=list, verbose_name="데이터 유형"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "error_details",
                    models.JSONField(default=dict, verbose_name="에러 상세"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_histories",
                        to="integration.erpintegration",
                        verbose_name="연계 시스템",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="실행자",
                    ),
                ),
            ],
            options={
                "verbose_name": "연계 이력",
                "verbose_name_plural": "연계 이력",
                "db_table": "integration_histories",
                "ordering": ["-start_time"],
            },
        ),
    ]
