# Generated by Django 4.2.7 on 2026-01-16 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="설비 코드"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="설비명")),
                ("type", models.CharField(max_length=100, verbose_name="설비 유형")),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="제조사"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="모델")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="시리얼 번호"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="설치 위치"),
                ),
                ("installation_date", models.DateField(verbose_name="설치일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "가동중"),
                            ("MAINTENANCE", "정비중"),
                            ("DAMAGED", "고장"),
                            ("RETIRED", "폐기"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="담당 부서"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="취득 비용"
                    ),
                ),
                ("specifications", models.JSONField(default=dict, verbose_name="사양")),
                (
                    "health_score",
                    models.IntegerField(default=100, verbose_name="건강 점수"),
                ),
                (
                    "predicted_failure_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="예상 잔존 수명(일)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "설비",
                "verbose_name_plural": "설비",
                "db_table": "equipment",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PreventiveMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="작업 번호"
                    ),
                ),
                ("task_name", models.CharField(max_length=200, verbose_name="작업명")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "일일"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("QUARTERLY", "분기"),
                            ("YEARLY", "연간"),
                            ("CUSTOM", "사용자"),
                        ],
                        max_length=20,
                        verbose_name="주기",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="예정일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ASSIGNED", "할당"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("OVERDUE", "지연"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(verbose_name="예상 소요시간(분)"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "중간"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "last_completed",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 완료일"
                    ),
                ),
                ("next_due", models.DateField(verbose_name="다음 예정일")),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="완료 메모"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pm_tasks",
                        to="equipment.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "예방 보전",
                "verbose_name_plural": "예방 보전",
                "db_table": "preventive_maintenances",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentRepairHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair_date", models.DateField(verbose_name="수리일")),
                (
                    "repair_type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "고장 수리"),
                            ("PREVENTIVE", "예방 정비"),
                            ("PREDICTIVE", "예지 보전"),
                            ("EMERGENCY", "긴급 수리"),
                        ],
                        max_length=20,
                        verbose_name="수리 유형",
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "parts_used",
                    models.JSONField(default=list, verbose_name="사용 부품"),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="인건비",
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="부품비",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="총비용",
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="다운타임(시간)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_repairs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_histories",
                        to="equipment.equipment",
                        verbose_name="설비",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_repairs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보고자",
                    ),
                ),
            ],
            options={
                "verbose_name": "설비 수리 이력",
                "verbose_name_plural": "설비 수리 이력",
                "db_table": "equipment_repair_histories",
                "ordering": ["-repair_date"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="부품 코드"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="부품명")),
                (
                    "part_number",
                    models.CharField(max_length=100, verbose_name="부품 번호"),
                ),
                ("specifications", models.TextField(verbose_name="사양")),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="재고 수량"),
                ),
                (
                    "min_stock",
                    models.IntegerField(default=10, verbose_name="최소 재고"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="단가"
                    ),
                ),
                ("supplier", models.CharField(max_length=100, verbose_name="공급사")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="보관 위치"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="equipment.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "설비 부품",
                "verbose_name_plural": "설비 부품",
                "db_table": "equipment_parts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("WORD", "Word"),
                            ("EXCEL", "Excel"),
                            ("IMAGE", "이미지"),
                        ],
                        max_length=20,
                        verbose_name="파일 유형",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="파일 경로"),
                ),
                ("file_size", models.IntegerField(verbose_name="파일 크기(bytes)")),
                ("version", models.CharField(max_length=20, verbose_name="버전")),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuals",
                        to="equipment.equipment",
                        verbose_name="설비",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "설비 매뉴얼",
                "verbose_name_plural": "설비 매뉴얼",
                "db_table": "equipment_manuals",
                "ordering": ["-upload_date"],
            },
        ),
    ]
