# Generated by Django 6.0.1 on 2026-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True, verbose_name="Token")),
                (
                    "jti",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="JWT ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Blacklisted At"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
            ],
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
                "db_table": "spc_blacklisted_token",
                "indexes": [
                    models.Index(fields=["jti"], name="spc_blackli_jti_f355fd_idx"),
                    models.Index(
                        fields=["user_id", "-blacklisted_at"],
                        name="spc_blackli_user_id_d74242_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="spc_blackli_expires_273c03_idx"
                    ),
                ],
            },
        ),
    ]
