# Generated by Django 6.0 on 2026-01-01 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlgorithmComparison",
            fields=[
                ("comparison_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job_count", models.IntegerField()),
                ("machine_count", models.IntegerField()),
                ("ga_makespan", models.FloatField(blank=True, null=True)),
                ("ga_tardiness", models.FloatField(blank=True, null=True)),
                ("ga_cost", models.FloatField(blank=True, null=True)),
                ("ga_runtime", models.FloatField(blank=True, null=True)),
                ("dispatch_results", models.JSONField(blank=True, null=True)),
                ("best_rule", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "algorithm_comparison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConstraintTemplate",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("constraint_type", models.CharField(max_length=50)),
                ("template_parameters", models.JSONField(default=dict)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "constraint_template",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION_SUMMARY", "Production Summary"),
                            ("PERFORMANCE_ANALYSIS", "Performance Analysis"),
                            ("QUALITY_REPORT", "Quality Report"),
                            ("SCHEDULE_ADHERENCE", "Schedule Adherence"),
                            ("BOTTLENECK_ANALYSIS", "Bottleneck Analysis"),
                            ("OEE_REPORT", "OEE Report"),
                            ("MACHINE_UTILIZATION", "Machine Utilization"),
                            ("ALERT_SUMMARY", "Alert Summary"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("default_filters", models.JSONField(blank=True, default=dict)),
                ("sections", models.JSONField(blank=True, default=list)),
                ("chart_types", models.JSONField(blank=True, default=list)),
                ("include_charts", models.BooleanField(default=True)),
                ("include_summary", models.BooleanField(default=True)),
                ("include_details", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "aps_report_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_editable", models.BooleanField(default=True)),
                ("requires_restart", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "aps_system_configuration",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("setting_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light"),
                            ("DARK", "Dark"),
                            ("AUTO", "Auto"),
                        ],
                        default="LIGHT",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ko", "Korean"),
                            ("en", "English"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                        ],
                        default="ko",
                        max_length=10,
                    ),
                ),
                (
                    "user_timezone",
                    models.CharField(default="Asia/Seoul", max_length=50),
                ),
                (
                    "default_dashboard",
                    models.CharField(default="enhanced", max_length=50),
                ),
                ("dashboard_refresh_interval", models.IntegerField(default=30)),
                ("show_kpi_cards", models.BooleanField(default=True)),
                ("kpi_card_order", models.JSONField(blank=True, default=list)),
                (
                    "gantt_view_mode",
                    models.CharField(
                        choices=[
                            ("DAY", "Day View"),
                            ("WEEK", "Week View"),
                            ("MONTH", "Month View"),
                        ],
                        default="WEEK",
                        max_length=20,
                    ),
                ),
                ("gantt_show_dependencies", models.BooleanField(default=True)),
                (
                    "gantt_color_scheme",
                    models.CharField(default="status", max_length=50),
                ),
                ("enable_notifications", models.BooleanField(default=True)),
                ("notification_sound", models.BooleanField(default=True)),
                ("alert_threshold_critical", models.IntegerField(default=1)),
                ("alert_threshold_warning", models.IntegerField(default=3)),
                ("email_notifications", models.BooleanField(default=False)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                (
                    "default_algorithm",
                    models.CharField(
                        choices=[
                            ("GA", "Genetic Algorithm"),
                            ("FIFO", "First In First Out"),
                            ("SPT", "Shortest Processing Time"),
                            ("EDD", "Earliest Due Date"),
                        ],
                        default="GA",
                        max_length=50,
                    ),
                ),
                ("ga_population_size", models.IntegerField(default=50)),
                ("ga_generations", models.IntegerField(default=100)),
                ("ga_mutation_rate", models.FloatField(default=0.1)),
                ("items_per_page", models.IntegerField(default=20)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=50)),
                (
                    "time_format",
                    models.CharField(
                        choices=[("24H", "24 Hour"), ("12H", "12 Hour")],
                        default="24H",
                        max_length=10,
                    ),
                ),
                ("number_format", models.CharField(default="1,234.56", max_length=20)),
                ("advanced_features_enabled", models.BooleanField(default=False)),
                ("developer_mode", models.BooleanField(default=False)),
                ("auto_save", models.BooleanField(default=True)),
                ("auto_save_interval", models.IntegerField(default=300)),
                ("custom_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "aps_user_settings",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production Issue"),
                            ("QUALITY", "Quality Issue"),
                            ("SCHEDULE", "Schedule Deviation"),
                            ("MACHINE", "Machine Issue"),
                            ("MATERIAL", "Material Issue"),
                            ("CONSTRAINT", "Constraint Violation"),
                            ("SYSTEM", "System Issue"),
                        ],
                        default="SYSTEM",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("mc_cd", models.CharField(blank=True, db_index=True, max_length=50)),
                ("wo_no", models.CharField(blank=True, max_length=100)),
                ("related_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("recommended_action", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("acknowledged_by", models.CharField(blank=True, max_length=100)),
                ("resolved_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "aps_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "status"],
                        name="aps_alert_severit_e87d2b_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="aps_alert_categor_e56754_idx",
                    ),
                    models.Index(
                        fields=["mc_cd", "-created_at"],
                        name="aps_alert_mc_cd_7c1047_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BottleneckAnalysis",
            fields=[
                ("analysis_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("mc_cd", models.CharField(db_index=True, max_length=20)),
                ("utilization_rate", models.FloatField()),
                ("queue_length", models.IntegerField(default=0)),
                ("avg_waiting_time", models.FloatField(default=0)),
                ("bottleneck_score", models.FloatField(default=0)),
                ("is_bottleneck", models.BooleanField(default=False)),
                ("affected_jobs", models.IntegerField(default=0)),
                ("total_delay", models.FloatField(default=0)),
                ("recommendations", models.JSONField(blank=True, null=True)),
                ("analysis_start", models.DateTimeField()),
                ("analysis_end", models.DateTimeField()),
            ],
            options={
                "db_table": "bottleneck_analysis",
                "ordering": ["-created_at", "-bottleneck_score"],
                "indexes": [
                    models.Index(
                        fields=["mc_cd", "created_at"], name="ix_bottleneck_mc_ts"
                    ),
                    models.Index(fields=["is_bottleneck"], name="ix_bottleneck_flag"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                ("constraint_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("MACHINE_AVAILABILITY", "Machine Availability"),
                            ("PRECEDENCE", "Precedence"),
                            ("SETUP_TIME", "Setup Time"),
                            ("SKILL_REQUIREMENT", "Skill Requirement"),
                            ("MATERIAL_AVAILABILITY", "Material Availability"),
                            ("CAPACITY_LIMIT", "Capacity Limit"),
                            ("TIME_WINDOW", "Time Window"),
                            ("BATCH_SIZE", "Batch Size"),
                            ("RESOURCE_CONFLICT", "Resource Conflict"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("parameters", models.JSONField(default=dict)),
                ("machines", models.JSONField(blank=True, null=True)),
                ("jobs", models.JSONField(blank=True, null=True)),
                ("items", models.JSONField(blank=True, null=True)),
                ("allow_violation", models.BooleanField(default=False)),
                ("violation_penalty", models.FloatField(default=1000.0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "constraint",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["constraint_type", "is_active"],
                        name="ix_constraint_type_active",
                    ),
                    models.Index(fields=["priority"], name="ix_constraint_priority"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConstraintGroup",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("apply_all", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "constraints",
                    models.ManyToManyField(related_name="groups", to="aps.constraint"),
                ),
            ],
            options={
                "db_table": "constraint_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobSequence",
            fields=[
                ("sequence_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("mc_cd", models.CharField(blank=True, db_index=True, max_length=50)),
                ("job_sequence", models.JSONField(default=list)),
                (
                    "sequencing_rule",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Order"),
                            ("FIFO", "First In First Out"),
                            ("LIFO", "Last In First Out"),
                            ("SPT", "Shortest Processing Time"),
                            ("LPT", "Longest Processing Time"),
                            ("EDD", "Earliest Due Date"),
                            ("SLACK", "Minimum Slack"),
                            ("CR", "Critical Ratio"),
                            ("WSPT", "Weighted Shortest Processing Time"),
                            ("ATC", "Apparent Tardiness Cost"),
                        ],
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                ("estimated_makespan", models.FloatField(blank=True, null=True)),
                ("estimated_tardiness", models.FloatField(blank=True, null=True)),
                ("estimated_flowtime", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "aps_job_sequence",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mc_cd", "status"], name="aps_job_seq_mc_cd_f43eb3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="aps_job_seq_created_1017f2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("total_output", models.IntegerField(default=0)),
                ("total_planned", models.IntegerField(default=0)),
                ("plan_achievement_rate", models.FloatField(default=0.0)),
                ("total_defects", models.IntegerField(default=0)),
                ("overall_yield_rate", models.FloatField(default=100.0)),
                ("first_pass_yield", models.FloatField(default=100.0)),
                ("avg_utilization", models.FloatField(default=0.0)),
                ("avg_oee", models.FloatField(default=0.0)),
                ("machines_running", models.IntegerField(default=0)),
                ("machines_idle", models.IntegerField(default=0)),
                ("machines_down", models.IntegerField(default=0)),
                ("jobs_completed", models.IntegerField(default=0)),
                ("jobs_in_progress", models.IntegerField(default=0)),
                ("jobs_delayed", models.IntegerField(default=0)),
                ("on_time_delivery_rate", models.FloatField(default=100.0)),
                ("active_alerts", models.IntegerField(default=0)),
                ("critical_alerts", models.IntegerField(default=0)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("REALTIME", "Real-time"),
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                        ],
                        default="REALTIME",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "aps_kpi_snapshot",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="aps_kpi_sna_timesta_c11a44_idx"
                    ),
                    models.Index(
                        fields=["snapshot_type", "-timestamp"],
                        name="aps_kpi_sna_snapsho_8dbbfe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MachineLoadHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("mc_cd", models.CharField(db_index=True, max_length=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("active_jobs", models.IntegerField(default=0)),
                ("queued_jobs", models.IntegerField(default=0)),
                ("utilization_rate", models.FloatField(default=0)),
                ("total_capacity", models.FloatField(default=0)),
                ("used_capacity", models.FloatField(default=0)),
                ("available_capacity", models.FloatField(default=0)),
            ],
            options={
                "db_table": "machine_load_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["mc_cd", "timestamp"], name="ix_load_mc_ts")
                ],
            },
        ),
        migrations.CreateModel(
            name="MachineMetrics",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("mc_cd", models.CharField(db_index=True, max_length=50)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[
                            ("MINUTE", "Minute"),
                            ("HOUR", "Hour"),
                            ("DAY", "Day"),
                        ],
                        default="HOUR",
                        max_length=20,
                    ),
                ),
                ("output_quantity", models.IntegerField(default=0)),
                ("defect_quantity", models.IntegerField(default=0)),
                ("yield_rate", models.FloatField(default=100.0)),
                ("runtime_minutes", models.FloatField(default=0.0)),
                ("downtime_minutes", models.FloatField(default=0.0)),
                ("setup_time_minutes", models.FloatField(default=0.0)),
                ("utilization_rate", models.FloatField(default=0.0)),
                ("avg_cycle_time", models.FloatField(default=0.0)),
                ("target_cycle_time", models.FloatField(default=0.0)),
                ("performance_rate", models.FloatField(default=100.0)),
                ("availability", models.FloatField(default=100.0)),
                ("performance", models.FloatField(default=100.0)),
                ("quality", models.FloatField(default=100.0)),
                ("oee", models.FloatField(default=100.0)),
                ("aggregated_from_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "aps_machine_metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["mc_cd", "-timestamp"],
                        name="aps_machine_mc_cd_f60ab7_idx",
                    ),
                    models.Index(
                        fields=["bucket_type", "-timestamp"],
                        name="aps_machine_bucket__b9ddff_idx",
                    ),
                ],
                "unique_together": {("mc_cd", "timestamp", "bucket_type")},
            },
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                ("preset_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "preset_type",
                    models.CharField(
                        choices=[
                            ("ALGORITHM", "Algorithm Configuration"),
                            ("SCHEDULE", "Schedule Configuration"),
                            ("FILTER", "Filter Preset"),
                            ("VIEW", "View Preset"),
                            ("DASHBOARD", "Dashboard Layout"),
                        ],
                        max_length=50,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("owner", models.CharField(blank=True, max_length=100)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "aps_preset",
                "ordering": ["-is_favorite", "-last_used", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["preset_type", "owner"],
                        name="aps_preset_preset__d1a760_idx",
                    ),
                    models.Index(
                        fields=["is_public", "preset_type"],
                        name="aps_preset_is_publ_52067b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("mc_cd", models.CharField(db_index=True, max_length=50)),
                ("mc_nm", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("SETUP", "Setup"),
                            ("MAINTENANCE", "Maintenance"),
                            ("BREAKDOWN", "Breakdown"),
                            ("WAITING", "Waiting for Material"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("current_wo_no", models.CharField(blank=True, max_length=100)),
                ("current_item_cd", models.CharField(blank=True, max_length=100)),
                ("planned_quantity", models.IntegerField(default=0)),
                ("completed_quantity", models.IntegerField(default=0)),
                ("defect_quantity", models.IntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("job_start_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("current_cycle_time", models.FloatField(default=0.0)),
                ("average_cycle_time", models.FloatField(default=0.0)),
                ("utilization_rate", models.FloatField(default=0.0)),
                ("oee", models.FloatField(default=0.0)),
                ("has_alert", models.BooleanField(default=False)),
                ("alert_type", models.CharField(blank=True, max_length=50)),
                ("alert_message", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "aps_production_status",
                "ordering": ["mc_cd"],
                "indexes": [
                    models.Index(
                        fields=["mc_cd", "status"], name="aps_product_mc_cd_df764b_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="aps_product_last_up_37a1dc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION_SUMMARY", "Production Summary"),
                            ("PERFORMANCE_ANALYSIS", "Performance Analysis"),
                            ("QUALITY_REPORT", "Quality Report"),
                            ("SCHEDULE_ADHERENCE", "Schedule Adherence"),
                            ("BOTTLENECK_ANALYSIS", "Bottleneck Analysis"),
                            ("OEE_REPORT", "OEE Report"),
                            ("MACHINE_UTILIZATION", "Machine Utilization"),
                            ("ALERT_SUMMARY", "Alert Summary"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        default="PRODUCTION_SUMMARY",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("charts", models.JSONField(blank=True, default=list)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        default="PDF",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ONCE", "Once"),
                        ],
                        default="ONCE",
                        max_length=20,
                    ),
                ),
                ("next_run", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "aps_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="aps_report_report__1a84cb_idx",
                    ),
                    models.Index(
                        fields=["status"], name="aps_report_status_bc4b07_idx"
                    ),
                    models.Index(
                        fields=["is_scheduled", "next_run"],
                        name="aps_report_is_sche_ffb112_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("scenario_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("base_plan_date", models.DateTimeField(blank=True, null=True)),
                ("modifications", models.JSONField(blank=True, default=list)),
                ("algorithm", models.CharField(default="GA", max_length=50)),
                ("algorithm_params", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "baseline_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="aps.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioComparison",
            fields=[
                ("comparison_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("comparison_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "scenarios",
                    models.ManyToManyField(
                        related_name="comparisons", to="aps.scenario"
                    ),
                ),
            ],
            options={
                "db_table": "scenario_comparison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("makespan", models.FloatField(default=0)),
                ("total_tardiness", models.FloatField(default=0)),
                ("max_tardiness", models.FloatField(default=0)),
                ("avg_utilization", models.FloatField(default=0)),
                ("total_cost", models.FloatField(default=0)),
                ("total_jobs", models.IntegerField(default=0)),
                ("completed_jobs", models.IntegerField(default=0)),
                ("tardy_jobs", models.IntegerField(default=0)),
                ("total_machines", models.IntegerField(default=0)),
                ("avg_machine_utilization", models.FloatField(default=0)),
                ("bottleneck_machines", models.JSONField(blank=True, null=True)),
                ("schedule", models.JSONField(blank=True, null=True)),
                ("execution_time", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_results",
                        to="aps.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceComparison",
            fields=[
                ("comparison_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("comparison_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                (
                    "recommended_sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_comparisons",
                        to="aps.jobsequence",
                    ),
                ),
                (
                    "sequences",
                    models.ManyToManyField(
                        related_name="comparisons", to="aps.jobsequence"
                    ),
                ),
            ],
            options={
                "db_table": "aps_sequence_comparison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceOptimization",
            fields=[
                (
                    "optimization_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("mc_cd", models.CharField(blank=True, db_index=True, max_length=50)),
                ("job_ids", models.JSONField(default=list)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("MAKESPAN", "Minimize Makespan"),
                            ("TARDINESS", "Minimize Total Tardiness"),
                            ("FLOWTIME", "Minimize Total Flow Time"),
                            ("WEIGHTED_TARDINESS", "Minimize Weighted Tardiness"),
                            ("MULTI_OBJECTIVE", "Multi-Objective"),
                        ],
                        default="MAKESPAN",
                        max_length=50,
                    ),
                ),
                ("results", models.JSONField(default=list)),
                ("execution_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                (
                    "best_sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimizations",
                        to="aps.jobsequence",
                    ),
                ),
            ],
            options={
                "db_table": "aps_sequence_optimization",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("VIEW_PAGE", "Page View"),
                            ("CREATE", "Create Item"),
                            ("UPDATE", "Update Item"),
                            ("DELETE", "Delete Item"),
                            ("EXPORT", "Export Data"),
                            ("GENERATE_REPORT", "Generate Report"),
                            ("RUN_ALGORITHM", "Run Algorithm"),
                            ("SAVE_PRESET", "Save Preset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("page", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "db_table": "aps_user_activity",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "-timestamp"],
                        name="aps_user_ac_user_id_202b6f_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="aps_user_ac_activit_92757e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConstraintViolation",
            fields=[
                ("violation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("job", models.CharField(blank=True, max_length=30, null=True)),
                ("machine", models.CharField(blank=True, max_length=20, null=True)),
                ("violation_amount", models.FloatField(default=0)),
                ("penalty_cost", models.FloatField(default=0)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "constraint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="aps.constraint",
                    ),
                ),
            ],
            options={
                "db_table": "constraint_violation",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "is_resolved"], name="ix_violation_severity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportHistory",
            fields=[
                ("export_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULE", "Schedule Export"),
                            ("REPORT", "Report Export"),
                            ("DATA", "Raw Data Export"),
                            ("BACKUP", "Data Backup"),
                        ],
                        default="DATA",
                        max_length=50,
                    ),
                ),
                ("data_type", models.CharField(max_length=100)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("EXCEL", "Excel Spreadsheet"),
                            ("CSV", "CSV File"),
                            ("JSON", "JSON Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=100)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to="aps.report",
                    ),
                ),
            ],
            options={
                "db_table": "aps_export_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["export_type", "-created_at"],
                        name="aps_export__export__f10661_idx",
                    ),
                    models.Index(
                        fields=["data_type"], name="aps_export__data_ty_ffbfcc_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(
                fields=["status", "created_at"], name="ix_scenario_status_ts"
            ),
        ),
    ]
