# Generated by Django 6.0 on 2026-01-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("ANOMALY", "이상 징후"),
                            ("TREND", "트렌드 분석"),
                            ("PATTERN", "패턴 발견"),
                            ("OPPORTUNITY", "개선 기회"),
                            ("RISK", "리스크 경고"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("supporting_data", models.JSONField(blank=True, default=dict)),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("analysis_period_start", models.DateTimeField(blank=True, null=True)),
                ("analysis_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_insight",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("user_name", models.CharField(default="admin", max_length=100)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "chat_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEST_PRACTICE", "모범 사례"),
                            ("TROUBLESHOOTING", "문제 해결"),
                            ("OPTIMIZATION", "최적화 기법"),
                            ("MAINTENANCE", "유지보수"),
                            ("QUALITY", "품질 관리"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("view_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "knowledge_base",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("DEMAND_FORECAST", "수요 예측"),
                            ("MAINTENANCE_PREDICTION", "고장 예측"),
                            ("QUALITY_PREDICTION", "품질 예측"),
                            ("DELIVERY_PREDICTION", "납기 예측"),
                            ("RESOURCE_OPTIMIZATION", "리소스 최적화"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("algorithm", models.CharField(max_length=100)),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("mae", models.FloatField(default=0.0)),
                ("rmse", models.FloatField(default=0.0)),
                ("training_data_size", models.IntegerField(default=0)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "학습중"),
                            ("ACTIVE", "활성"),
                            ("DEPRECATED", "사용중지"),
                        ],
                        default="TRAINING",
                        max_length=20,
                    ),
                ),
                ("model_file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "predictive_model",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULE_OPTIMIZATION", "스케줄 최적화"),
                            ("RESOURCE_ALLOCATION", "리소스 할당"),
                            ("MAINTENANCE_TIMING", "유지보수 시기"),
                            ("PRIORITY_ADJUSTMENT", "우선순위 조정"),
                            ("BOTTLENECK_RESOLUTION", "병목 해소"),
                            ("QUALITY_IMPROVEMENT", "품질 개선"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("reasoning", models.TextField()),
                ("expected_benefit", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("affected_jobs", models.JSONField(blank=True, default=list)),
                ("affected_machines", models.JSONField(blank=True, default=list)),
                ("suggested_action", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "낮음"), (2, "보통"), (3, "높음"), (4, "긴급")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ACCEPTED", "수락"),
                            ("REJECTED", "거부"),
                            ("APPLIED", "적용됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("applied_by", models.CharField(blank=True, max_length=100)),
                ("actual_benefit", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "smart_recommendation",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "사용자"),
                            ("ASSISTANT", "AI 어시스턴트"),
                            ("SYSTEM", "시스템"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("referenced_jobs", models.JSONField(blank=True, default=list)),
                ("referenced_machines", models.JSONField(blank=True, default=list)),
                ("referenced_data", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aps.chatconversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_type", models.CharField(max_length=50)),
                ("target_entity", models.CharField(blank=True, max_length=100)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("predicted_value", models.FloatField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("predicted_date", models.DateTimeField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("is_accurate", models.BooleanField(blank=True, null=True)),
                ("features_used", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="aps.predictivemodel",
                    ),
                ),
            ],
            options={
                "db_table": "prediction",
                "ordering": ["-created_at"],
            },
        ),
    ]
