# Generated by Django 6.0 on 2026-01-09 03:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0002_aiinsight_chatconversation_knowledgebase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prediction",
            name="prediction_type",
            field=models.CharField(
                choices=[
                    ("PROC_TIME", "Process Time"),
                    ("SETUP_TIME", "Setup Time"),
                    ("DOWN_RISK", "Downtime Risk"),
                    ("DEMAND", "Demand Forecast"),
                    ("QUALITY", "Quality Prediction"),
                    ("DELIVERY", "Delivery Prediction"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OperationActual",
            fields=[
                ("actual_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wo_no",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="작업지시번호"
                    ),
                ),
                ("op_seq", models.IntegerField(verbose_name="공정순서")),
                (
                    "operation_nm",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                (
                    "resource_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="설비코드"
                    ),
                ),
                ("planned_start_dt", models.DateTimeField(verbose_name="계획시작일시")),
                ("planned_end_dt", models.DateTimeField(verbose_name="계획종료일시")),
                (
                    "planned_duration_minutes",
                    models.IntegerField(verbose_name="계획소요시간(분)"),
                ),
                (
                    "actual_start_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제시작일시"
                    ),
                ),
                (
                    "actual_end_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제종료일시"
                    ),
                ),
                (
                    "actual_duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="실제소요시간(분)"
                    ),
                ),
                (
                    "proc_time_hr",
                    models.FloatField(
                        blank=True,
                        help_text="DOWN_RISK 계산에 사용",
                        null=True,
                        verbose_name="실제작업시간(시간)",
                    ),
                ),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="계획수량",
                    ),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="실제수량",
                    ),
                ),
                (
                    "good_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="양품수량",
                    ),
                ),
                (
                    "defect_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="불량수량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "계획"),
                            ("STARTED", "시작"),
                            ("PAUSED", "일시중지"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                            ("DELAYED", "지연"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False,
                        help_text="계획 대비 크게 지연된 작업",
                        verbose_name="비정상여부",
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="actual - planned",
                        verbose_name="지연시간(분)",
                    ),
                ),
                (
                    "delay_reason",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="지연사유"
                    ),
                ),
                (
                    "down_events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{type, start, end, reason}]",
                        verbose_name="다운타임이벤트",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "작업실적",
                "verbose_name_plural": "작업실적",
                "db_table": "operation_actual",
                "ordering": ["-actual_start_dt"],
                "indexes": [
                    models.Index(
                        fields=["resource_code", "actual_start_dt"],
                        name="ix_actual_res_dt",
                    ),
                    models.Index(fields=["wo_no", "op_seq"], name="ix_actual_wo_seq"),
                    models.Index(
                        fields=["status", "is_abnormal"], name="ix_actual_status_abn"
                    ),
                    models.Index(fields=["actual_start_dt"], name="ix_actual_start"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DOWN_BREAKDOWN", "고장"),
                            ("DOWN_MAINTENANCE", "정비"),
                            ("DOWN_MATERIAL", "자재부족"),
                            ("DOWN_QUALITY", "품질이슈"),
                            ("DOWN_CHANGEOVER", "전환"),
                            ("DOWN_OTHER", "기타"),
                            ("SETUP", "준비"),
                            ("IDLE", "유휴"),
                            ("RUNNING", "가동"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="이벤트유형",
                    ),
                ),
                (
                    "resource_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="설비코드"
                    ),
                ),
                (
                    "start_dt",
                    models.DateTimeField(db_index=True, verbose_name="시작일시"),
                ),
                (
                    "end_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료일시"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="소요시간(분)"
                    ),
                ),
                (
                    "wo_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="작업지시번호",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="사유"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세설명"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "심각"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="조치내용"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="해결여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "operation_actual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="aps.operationactual",
                        verbose_name="연관작업",
                    ),
                ),
            ],
            options={
                "verbose_name": "실행이벤트",
                "verbose_name_plural": "실행이벤트",
                "db_table": "execution_event",
                "ordering": ["-start_dt"],
                "indexes": [
                    models.Index(
                        fields=["resource_code", "start_dt"], name="ix_event_res_dt"
                    ),
                    models.Index(
                        fields=["event_type", "severity"], name="ix_event_type_sev"
                    ),
                    models.Index(fields=["start_dt"], name="ix_event_start"),
                ],
            },
        ),
    ]
