# Generated by Django 4.2.7 on 2026-01-16 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="작업지시 번호"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="제품 코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                ("quantity", models.IntegerField(verbose_name="생산 수량")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ASSIGNED", "할당"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                            ("ON_HOLD", "보류"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "중간"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("target_end_date", models.DateField(verbose_name="목표 완료일")),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 완료일"),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="진행률(%)"),
                ),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="완료 수량"),
                ),
                (
                    "predicted_completion_risk",
                    models.CharField(
                        choices=[("LOW", "낮음"), ("MEDIUM", "중간"), ("HIGH", "높음")],
                        default="LOW",
                        max_length=20,
                        verbose_name="완료 위험도",
                    ),
                ),
                (
                    "risk_reasons",
                    models.JSONField(default=list, verbose_name="위험도 사유"),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="예상 비용",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="실제 비용",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="equipment.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업지시",
                "verbose_name_plural": "작업지시",
                "db_table": "work_orders",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="시간"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ASSIGNED", "할당"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                            ("ON_HOLD", "보류"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("progress_percentage", models.IntegerField(verbose_name="진행률(%)")),
                (
                    "completed_quantity",
                    models.IntegerField(default=0, verbose_name="완료 수량"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보고자",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="work_orders.workorder",
                        verbose_name="작업지시",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업지시 진행 상황",
                "verbose_name_plural": "작업지시 진행 상황",
                "db_table": "work_order_progress",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    models.IntegerField(default=1, verbose_name="필요 수량"),
                ),
                (
                    "usage_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="사용 시간(시간)",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_tools",
                        to="tools.tool",
                        verbose_name="치공구",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_tools",
                        to="work_orders.workorder",
                        verbose_name="작업지시",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업지시 치공구",
                "verbose_name_plural": "작업지시 치공구",
                "db_table": "work_order_tools",
                "unique_together": {("work_order", "tool")},
            },
        ),
    ]
