# Generated by Django 4.2.7 on 2026-01-16 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="치공구 코드"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="치공구명")),
                ("type", models.CharField(max_length=100, verbose_name="치공구 유형")),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="제조사"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="모델")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="시리얼 번호"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="보관 위치"),
                ),
                ("purchase_date", models.DateField(verbose_name="구입일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "사용 가능"),
                            ("IN_USE", "사용중"),
                            ("MAINTENANCE", "정비중"),
                            ("DAMAGED", "고장"),
                            ("RETIRED", "폐기"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="담당 부서"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="취득 비용"
                    ),
                ),
                ("specifications", models.JSONField(default=dict, verbose_name="사양")),
                (
                    "expected_life_days",
                    models.IntegerField(verbose_name="예상 수명(일)"),
                ),
                (
                    "predicted_remaining_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="예상 잔존 수명(일)"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "total_usage_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="총 사용 시간(시간)",
                    ),
                ),
                (
                    "optimal_replacement_date",
                    models.DateField(blank=True, null=True, verbose_name="최적 교체일"),
                ),
                (
                    "last_replacement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 교체일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "치공구",
                "verbose_name_plural": "치공구",
                "db_table": "tools",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ToolRepairHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair_date", models.DateField(verbose_name="수리일")),
                (
                    "repair_type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "고장 수리"),
                            ("PREVENTIVE", "예방 정비"),
                            ("REPLACEMENT", "교체"),
                            ("REFURBISHMENT", "재생"),
                        ],
                        max_length=20,
                        verbose_name="수리 유형",
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="인건비",
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="부품비",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="총비용",
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="다운타임(시간)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tool_repairs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_tool_repairs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보고자",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_histories",
                        to="tools.tool",
                        verbose_name="치공구",
                    ),
                ),
            ],
            options={
                "verbose_name": "치공구 수리 이력",
                "verbose_name_plural": "치공구 수리 이력",
                "db_table": "tool_repair_histories",
                "ordering": ["-repair_date"],
            },
        ),
    ]
