# Generated by Django 4.2.7 on 2026-01-16 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="이슈 번호"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="제품 코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "defect_type",
                    models.CharField(max_length=100, verbose_name="불량 유형"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "중간"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        max_length=20,
                        verbose_name="중요도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "접수"),
                            ("INVESTIGATING", "조사중"),
                            ("IN_PROGRESS", "진행중"),
                            ("RESOLVED", "해결"),
                            ("CLOSED", "종결"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "reported_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="보고일"),
                ),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="불량 수량"),
                ),
                (
                    "cost_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="비용 영향",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                (
                    "target_resolution_date",
                    models.DateField(verbose_name="목표 해결일"),
                ),
                (
                    "actual_resolution_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 해결일"),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="완료 메모"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="보고자",
                    ),
                ),
            ],
            options={
                "verbose_name": "품질 이슈",
                "verbose_name_plural": "품질 이슈",
                "db_table": "quality_issues",
                "ordering": ["-reported_date"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSolvingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(verbose_name="단계")),
                ("step_name", models.CharField(max_length=100, verbose_name="단계명")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solving_steps",
                        to="quality_issues.qualityissue",
                        verbose_name="품질 이슈",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 해결 단계",
                "verbose_name_plural": "문제 해결 단계",
                "db_table": "problem_solving_steps",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="IssueAnalysis4M",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MAN", "사람"),
                            ("MACHINE", "설비"),
                            ("MATERIAL", "자재"),
                            ("METHOD", "방법"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("description", models.TextField(verbose_name="분석 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses_4m",
                        to="quality_issues.qualityissue",
                        verbose_name="품질 이슈",
                    ),
                ),
            ],
            options={
                "verbose_name": "4M 분석",
                "verbose_name_plural": "4M 분석",
                "db_table": "issue_analysis_4m",
            },
        ),
    ]
