# Generated by Django 4.2.7 on 2026-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_id",
                    models.CharField(
                        help_text="AI 인사이트 ID", max_length=50, unique=True
                    ),
                ),
                ("period", models.CharField(help_text="기간 (YYYY-MM)", max_length=7)),
                ("title", models.CharField(help_text="인사이트 제목", max_length=200)),
                ("summary", models.TextField(help_text="인사이트 요약")),
                ("confidence", models.FloatField(help_text="신뢰도 (0-1)")),
                (
                    "insight_type",
                    models.CharField(
                        help_text="인사이트 유형 (PREDICTION/ANOMALY/OPTIMIZATION/RISK)",
                        max_length=20,
                    ),
                ),
                (
                    "actionable",
                    models.BooleanField(default=True, help_text="실행 가능 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Insight",
                "verbose_name_plural": "AI Insights",
                "db_table": "ai_insight",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(help_text="이벤트 ID", max_length=50, unique=True),
                ),
                ("type", models.CharField(help_text="알림 유형", max_length=20)),
                ("severity", models.IntegerField(help_text="심각도 (1-5)")),
                ("title", models.CharField(help_text="알림 제목", max_length=200)),
                ("description", models.TextField(blank=True, help_text="상세 설명")),
                (
                    "status",
                    models.CharField(
                        default="OPEN",
                        help_text="상태 (OPEN/INVESTIGATING/CLOSED)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(help_text="기간 (YYYY-MM)", max_length=7)),
                ("copq_rate", models.FloatField(help_text="COPQ 비율")),
                ("total_copq", models.IntegerField(help_text="총 COPQ 금액")),
                ("total_qcost", models.IntegerField(help_text="총 품질 비용")),
                ("oos_count", models.IntegerField(help_text="OOS 발생 횟수")),
                (
                    "spc_open_events",
                    models.IntegerField(help_text="SPC 오픈 이벤트 수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard KPI",
                "verbose_name_plural": "Dashboard KPIs",
                "db_table": "dashboard_kpi",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="TopDefect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(help_text="기간 (YYYY-MM)", max_length=7)),
                ("defect", models.CharField(help_text="불량 유형", max_length=100)),
                ("count", models.IntegerField(help_text="발생 횟수")),
                ("cost", models.IntegerField(help_text="불량 비용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Top Defect",
                "verbose_name_plural": "Top Defects",
                "db_table": "top_defect",
                "ordering": ["-period", "-count"],
            },
        ),
    ]
