# Generated by Django 4.2.7 on 2026-01-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_id",
                    models.CharField(
                        help_text="프로세스 흐름 ID", max_length=50, unique=True
                    ),
                ),
                ("product_id", models.CharField(help_text="제품 ID", max_length=50)),
                ("version", models.CharField(help_text="버전", max_length=20)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Process Flow",
                "verbose_name_plural": "Process Flows",
                "db_table": "process_flow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_id",
                    models.CharField(help_text="단계 ID", max_length=50, unique=True),
                ),
                ("step_order", models.IntegerField(help_text="순서")),
                ("step_name", models.CharField(help_text="공정명", max_length=100)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("IQC", "입고검사"),
                            ("IPQC", "공정검사"),
                            ("FQC", "최종검사"),
                            ("OQC", "출하검사"),
                        ],
                        help_text="검사 유형",
                        max_length=10,
                    ),
                ),
                ("criteria", models.JSONField(help_text="검사 기준 (JSON)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="프로세스 흐름",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="inspection.processflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Step",
                "verbose_name_plural": "Process Steps",
                "db_table": "process_step",
                "ordering": ["flow", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="InspectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(help_text="실시 ID", max_length=50, unique=True),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "정검사"),
                            ("R&A", "R&A"),
                            ("RED_TAG", "RED TAG"),
                        ],
                        help_text="실시 유형",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("JUDGED", "Judged"),
                        ],
                        default="OPEN",
                        help_text="상태",
                        max_length=20,
                    ),
                ),
                (
                    "inspector_id",
                    models.CharField(help_text="검사원 ID", max_length=50),
                ),
                ("started_at", models.DateTimeField(help_text="시작일시")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="완료일시", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="프로세스 흐름",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="inspection.processflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Run",
                "verbose_name_plural": "Inspection Runs",
                "db_table": "inspection_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_id",
                    models.CharField(help_text="결과 ID", max_length=50, unique=True),
                ),
                ("sample_id", models.CharField(help_text="표본 ID", max_length=50)),
                ("measurement_value", models.FloatField(help_text="측정값")),
                (
                    "is_oos",
                    models.BooleanField(default=False, help_text="규격 이탈 여부"),
                ),
                ("measured_at", models.DateTimeField(help_text="측정일시")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        help_text="검사 실시",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="inspection.inspectionrun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="프로세스 단계",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="inspection.processstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Result",
                "verbose_name_plural": "Inspection Results",
                "db_table": "inspection_result",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProcessDesignHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design_id",
                    models.CharField(help_text="설계 ID", max_length=50, unique=True),
                ),
                ("product_description", models.TextField(help_text="제품 설명")),
                ("quality_requirements", models.TextField(help_text="품질 요구사항")),
                (
                    "production_volume",
                    models.CharField(blank=True, help_text="생산량", max_length=50),
                ),
                ("confidence", models.FloatField(help_text="신뢰도 (0-1)")),
                ("reasoning", models.TextField(help_text="설계 사유")),
                (
                    "is_applied",
                    models.BooleanField(default=False, help_text="적용 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposed_flow",
                    models.ForeignKey(
                        blank=True,
                        help_text="제안된 공정 흐름",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_designs",
                        to="inspection.processflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Process Design History",
                "verbose_name_plural": "AI Process Design Histories",
                "db_table": "ai_process_design_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
