# Generated by Django 6.0 on 2026-01-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERPSyncLog",
            fields=[
                ("sync_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("ITEM", "품목마스터"),
                            ("MACHINE", "기계마스터"),
                            ("WORKCENTER", "작업장마스터"),
                            ("BOM", "BOM"),
                            ("ROUTING", "라우팅"),
                            ("WORKORDER", "작업지시"),
                        ],
                        max_length=50,
                        verbose_name="동기화유형",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                            ("PARTIAL", "부분성공"),
                        ],
                        max_length=20,
                        verbose_name="동기화상태",
                    ),
                ),
                (
                    "records_total",
                    models.IntegerField(default=0, verbose_name="총건수"),
                ),
                (
                    "records_success",
                    models.IntegerField(default=0, verbose_name="성공건수"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="실패건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류메시지"),
                ),
                (
                    "sync_ts",
                    models.DateTimeField(auto_now_add=True, verbose_name="동기화시각"),
                ),
            ],
            options={
                "verbose_name": "ERP동기화로그",
                "verbose_name_plural": "ERP동기화로그",
                "db_table": "erp_sync_log",
                "ordering": ["-sync_ts"],
            },
        ),
        migrations.CreateModel(
            name="MasterWorkCenter",
            fields=[
                (
                    "wc_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="작업장코드",
                    ),
                ),
                ("wc_nm", models.CharField(max_length=200, verbose_name="작업장명")),
                ("plant_cd", models.CharField(max_length=20, verbose_name="공장코드")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "작업장마스터",
                "verbose_name_plural": "작업장마스터",
                "db_table": "master_workcenter",
            },
        ),
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                (
                    "itm_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="품목코드",
                    ),
                ),
                ("itm_nm", models.CharField(max_length=200, verbose_name="품목명")),
                ("itm_type", models.CharField(max_length=20, verbose_name="품목구분")),
                (
                    "itm_family",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="품목패밀리"
                    ),
                ),
                (
                    "std_cycle_time",
                    models.IntegerField(default=60, verbose_name="표준CT(분)"),
                ),
                (
                    "unit",
                    models.CharField(default="EA", max_length=20, verbose_name="단위"),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "품목마스터",
                "verbose_name_plural": "품목마스터",
                "db_table": "master_item",
                "indexes": [models.Index(fields=["itm_family"], name="ix_item_family")],
            },
        ),
        migrations.CreateModel(
            name="MasterMachine",
            fields=[
                (
                    "mc_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="기계코드",
                    ),
                ),
                ("mc_nm", models.CharField(max_length=200, verbose_name="기계명")),
                ("wc_cd", models.CharField(max_length=20, verbose_name="작업장코드")),
                ("mc_type", models.CharField(max_length=50, verbose_name="기계유형")),
                ("capacity", models.IntegerField(default=1, verbose_name="생산능력")),
                (
                    "cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=10,
                        verbose_name="시간당비용",
                    ),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "기계마스터",
                "verbose_name_plural": "기계마스터",
                "db_table": "master_machine",
                "indexes": [models.Index(fields=["wc_cd"], name="ix_machine_wc")],
            },
        ),
        migrations.CreateModel(
            name="MasterBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="소요량"
                    ),
                ),
                ("seq", models.IntegerField(default=1, verbose_name="순번")),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_parents",
                        to="erp.masteritem",
                        verbose_name="자품목",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_children",
                        to="erp.masteritem",
                        verbose_name="모품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM",
                "db_table": "master_bom",
                "unique_together": {("parent_item", "child_item")},
            },
        ),
        migrations.CreateModel(
            name="ERPWorkOrder",
            fields=[
                (
                    "wo_no",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="작업지시번호",
                    ),
                ),
                (
                    "order_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="지시수량"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="납기일")),
                (
                    "priority",
                    models.IntegerField(default=5, verbose_name="우선순위(1-10)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "생성"),
                            ("RELEASED", "출고"),
                            ("RUNNING", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="CREATED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("plant_cd", models.CharField(max_length=20, verbose_name="공장코드")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "erp_sync_ts",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP동기화시각"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.masteritem",
                        verbose_name="품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업지시",
                "verbose_name_plural": "작업지시",
                "db_table": "erp_workorder",
                "indexes": [
                    models.Index(fields=["status", "due_date"], name="ix_wo_status_due")
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField(verbose_name="공정순서")),
                (
                    "operation_nm",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                ("std_time", models.IntegerField(verbose_name="표준시간(분)")),
                (
                    "setup_time",
                    models.IntegerField(default=0, verbose_name="준비시간(분)"),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.masteritem",
                        verbose_name="품목",
                    ),
                ),
                (
                    "workcenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.masterworkcenter",
                        verbose_name="작업장",
                    ),
                ),
            ],
            options={
                "verbose_name": "라우팅",
                "verbose_name_plural": "라우팅",
                "db_table": "master_routing",
                "ordering": ["item", "seq"],
                "unique_together": {("item", "seq")},
            },
        ),
    ]
