# Generated by Django 6.0 on 2026-01-08 12:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterShift",
            fields=[
                (
                    "shift_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="작업조코드",
                    ),
                ),
                ("shift_nm", models.CharField(max_length=200, verbose_name="작업조명")),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("DAY", "주간"), ("NIGHT", "야간"), ("SWING", "교대")],
                        max_length=20,
                        verbose_name="작업조구분",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작시간")),
                ("end_time", models.TimeField(verbose_name="종료시간")),
                (
                    "break_time",
                    models.IntegerField(default=60, verbose_name="휴게시간(분)"),
                ),
                (
                    "is_overnight",
                    models.BooleanField(default=False, verbose_name="야간근무여부"),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "작업조마스터",
                "verbose_name_plural": "작업조마스터",
                "db_table": "master_shift",
            },
        ),
        migrations.CreateModel(
            name="MasterWorker",
            fields=[
                (
                    "worker_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="작업자코드",
                    ),
                ),
                (
                    "worker_nm",
                    models.CharField(max_length=200, verbose_name="작업자명"),
                ),
                (
                    "worker_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "정규직"),
                            ("CONTRACT", "계약직"),
                            ("TEMP", "임시직"),
                            ("DISPATCH", "파견직"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="작업자구분",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="입사일"),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="경력(년)"),
                ),
                (
                    "cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20000.00"),
                        max_digits=10,
                        verbose_name="시간당인건비",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연락처"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workers",
                        to="erp.mastershift",
                        verbose_name="소속작업조",
                    ),
                ),
                (
                    "workcenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="erp.masterworkcenter",
                        verbose_name="소속작업장",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업자마스터",
                "verbose_name_plural": "작업자마스터",
                "db_table": "master_worker",
            },
        ),
        migrations.CreateModel(
            name="MaterialRequirement",
            fields=[
                ("requirement_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wo_no",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="작업지시번호"
                    ),
                ),
                (
                    "required_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="소요량"
                    ),
                ),
                ("required_dt", models.DateTimeField(verbose_name="소요일시")),
                (
                    "allocated_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="할당량",
                    ),
                ),
                (
                    "shortage_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="부족량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ALLOCATED", "할당완료"),
                            ("SHORTAGE", "부족"),
                            ("ISSUED", "출고완료"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alternative_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternative_requirements",
                        to="erp.masteritem",
                        verbose_name="대체품목",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.masteritem",
                        verbose_name="품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "자재소요량",
                "verbose_name_plural": "자재소요량",
                "db_table": "material_requirement",
                "ordering": ["required_dt"],
            },
        ),
        migrations.CreateModel(
            name="PlantCalendar",
            fields=[
                ("calendar_id", models.AutoField(primary_key=True, serialize=False)),
                ("work_date", models.DateField(db_index=True, verbose_name="일자")),
                ("plant_cd", models.CharField(max_length=20, verbose_name="공장코드")),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("WORK", "근무일"),
                            ("HOLIDAY", "휴일"),
                            ("HALF_DAY", "반일근무"),
                            ("OVERTIME", "특근"),
                        ],
                        default="WORK",
                        max_length=20,
                        verbose_name="일자구분",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(default="08:00:00", verbose_name="근무시작시간"),
                ),
                (
                    "work_end_time",
                    models.TimeField(default="17:00:00", verbose_name="근무종료시간"),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="휴게시작시간"
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="휴게종료시간"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="가동가능여부"),
                ),
                (
                    "capacity_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        verbose_name="가동률(%)",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="비고"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "공장캘린더",
                "verbose_name_plural": "공장캘린더",
                "db_table": "plant_calendar",
                "ordering": ["work_date"],
                "indexes": [
                    models.Index(
                        fields=["work_date", "plant_cd"], name="ix_cal_date_plant"
                    ),
                    models.Index(
                        fields=["plant_cd", "day_type"], name="ix_cal_plant_type"
                    ),
                ],
                "unique_together": {("work_date", "plant_cd")},
            },
        ),
        migrations.CreateModel(
            name="WorkAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wo_no",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="작업지시번호"
                    ),
                ),
                ("operation_seq", models.IntegerField(verbose_name="공정순서")),
                (
                    "operation_nm",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                (
                    "assigned_start_dt",
                    models.DateTimeField(verbose_name="할당시작시간"),
                ),
                ("assigned_end_dt", models.DateTimeField(verbose_name="할당종료시간")),
                ("assigned_duration", models.IntegerField(verbose_name="할당시간(분)")),
                (
                    "actual_start_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제시작시간"
                    ),
                ),
                (
                    "actual_end_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제종료시간"
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="실제시간(분)"
                    ),
                ),
                (
                    "target_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="목표수량",
                    ),
                ),
                (
                    "actual_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="실제수량",
                    ),
                ),
                (
                    "good_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="양품수량",
                    ),
                ),
                (
                    "defect_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="불량수량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "할당"),
                            ("STARTED", "시작"),
                            ("PAUSED", "일시중지"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="erp.mastershift",
                        verbose_name="작업조",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="erp.masterworker",
                        verbose_name="담당작업자",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업할당",
                "verbose_name_plural": "작업할당",
                "db_table": "work_assignment",
                "ordering": ["assigned_start_dt"],
            },
        ),
        migrations.CreateModel(
            name="WorkerSkill",
            fields=[
                ("skill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "operation_nm",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                (
                    "skill_level",
                    models.IntegerField(
                        choices=[
                            (1, "초급"),
                            (2, "중급"),
                            (3, "고급"),
                            (4, "숙련"),
                            (5, "전문가"),
                        ],
                        verbose_name="숙련도",
                    ),
                ),
                (
                    "efficiency_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        verbose_name="작업효율(%)",
                    ),
                ),
                (
                    "certified_yn",
                    models.CharField(
                        default="N", max_length=1, verbose_name="자격증보유"
                    ),
                ),
                (
                    "certification_nm",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="자격증명"
                    ),
                ),
                (
                    "certification_date",
                    models.DateField(blank=True, null=True, verbose_name="자격취득일"),
                ),
                (
                    "training_hours",
                    models.IntegerField(default=0, verbose_name="교육시간(시간)"),
                ),
                (
                    "last_training_date",
                    models.DateField(blank=True, null=True, verbose_name="최종교육일"),
                ),
                (
                    "active_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="erp.masterworker",
                        verbose_name="작업자",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업자숙련도",
                "verbose_name_plural": "작업자숙련도",
                "db_table": "worker_skill",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("plant_cd", models.CharField(max_length=20, verbose_name="공장코드")),
                (
                    "warehouse_cd",
                    models.CharField(max_length=20, verbose_name="창고코드"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "입고"),
                            ("ISSUE", "출고"),
                            ("ADJUSTMENT", "조정"),
                            ("TRANSFER", "이동"),
                            ("RETURN", "반품"),
                        ],
                        max_length=20,
                        verbose_name="거래유형",
                    ),
                ),
                (
                    "transaction_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="거래일시"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="수량"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="단위원가",
                    ),
                ),
                (
                    "wo_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="작업지시번호",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="참조번호"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="비고"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.masteritem",
                        verbose_name="품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "재고이동이력",
                "verbose_name_plural": "재고이동이력",
                "db_table": "inventory_transaction",
                "ordering": ["-transaction_dt"],
                "indexes": [
                    models.Index(
                        fields=["item", "transaction_dt"], name="ix_invtx_item_dt"
                    ),
                    models.Index(
                        fields=["plant_cd", "transaction_dt"], name="ix_invtx_plant_dt"
                    ),
                    models.Index(fields=["wo_no"], name="ix_invtx_wo"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemInventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("plant_cd", models.CharField(max_length=20, verbose_name="공장코드")),
                (
                    "warehouse_cd",
                    models.CharField(
                        default="WH01", max_length=20, verbose_name="창고코드"
                    ),
                ),
                (
                    "on_hand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="현재고량",
                    ),
                ),
                (
                    "allocated_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="할당량",
                    ),
                ),
                (
                    "available_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="가용재고",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="안전재고",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="최소재고",
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="최대재고",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="재주문점",
                    ),
                ),
                (
                    "order_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="발주량",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="단위원가",
                    ),
                ),
                (
                    "inventory_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="재고금액",
                    ),
                ),
                (
                    "last_receipt_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최종입고일시"
                    ),
                ),
                (
                    "last_issue_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최종출고일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일시"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="erp.masteritem",
                        verbose_name="품목",
                    ),
                ),
            ],
            options={
                "verbose_name": "품목재고",
                "verbose_name_plural": "품목재고",
                "db_table": "item_inventory",
                "indexes": [
                    models.Index(fields=["item", "plant_cd"], name="ix_inv_item_plant"),
                    models.Index(
                        fields=["plant_cd", "warehouse_cd"], name="ix_inv_plant_wh"
                    ),
                ],
                "unique_together": {("item", "plant_cd", "warehouse_cd")},
            },
        ),
        migrations.CreateModel(
            name="MachineDowntime",
            fields=[
                ("downtime_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "downtime_type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "정기점검"),
                            ("REPAIR", "고장수리"),
                            ("SETUP", "셋업"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="다운타임구분",
                    ),
                ),
                (
                    "start_dt",
                    models.DateTimeField(db_index=True, verbose_name="시작일시"),
                ),
                (
                    "end_dt",
                    models.DateTimeField(db_index=True, verbose_name="종료일시"),
                ),
                (
                    "planned_yn",
                    models.CharField(
                        choices=[("Y", "계획"), ("N", "비계획")],
                        default="Y",
                        max_length=1,
                        verbose_name="계획여부",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세설명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtimes",
                        to="erp.mastermachine",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "설비다운타임",
                "verbose_name_plural": "설비다운타임",
                "db_table": "machine_downtime",
                "ordering": ["start_dt"],
                "indexes": [
                    models.Index(
                        fields=["machine", "start_dt"], name="ix_downtime_mc_start"
                    ),
                    models.Index(
                        fields=["start_dt", "end_dt"], name="ix_downtime_period"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MachineWorkTime",
            fields=[
                ("work_time_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작시간")),
                ("end_time", models.TimeField(verbose_name="종료시간")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="가동가능"),
                ),
                (
                    "is_overnight",
                    models.BooleanField(default=False, verbose_name="야간근무여부"),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="비고"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_times",
                        to="erp.mastermachine",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "설비가동시간",
                "verbose_name_plural": "설비가동시간",
                "db_table": "machine_work_time",
                "ordering": ["machine", "day_of_week"],
                "indexes": [
                    models.Index(
                        fields=["machine", "day_of_week"], name="ix_mwt_mc_dow"
                    )
                ],
                "unique_together": {("machine", "day_of_week")},
            },
        ),
        migrations.AddIndex(
            model_name="masterworker",
            index=models.Index(fields=["workcenter"], name="ix_worker_wc"),
        ),
        migrations.AddIndex(
            model_name="masterworker",
            index=models.Index(fields=["shift"], name="ix_worker_shift"),
        ),
        migrations.AddIndex(
            model_name="materialrequirement",
            index=models.Index(fields=["wo_no", "item"], name="ix_mrp_wo_item"),
        ),
        migrations.AddIndex(
            model_name="materialrequirement",
            index=models.Index(fields=["required_dt"], name="ix_mrp_req_dt"),
        ),
        migrations.AddIndex(
            model_name="materialrequirement",
            index=models.Index(fields=["status"], name="ix_mrp_status"),
        ),
        migrations.AddIndex(
            model_name="workassignment",
            index=models.Index(
                fields=["wo_no", "operation_seq"], name="ix_assign_wo_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="workassignment",
            index=models.Index(
                fields=["worker", "assigned_start_dt"], name="ix_assign_worker_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="workassignment",
            index=models.Index(
                fields=["shift", "assigned_start_dt"], name="ix_assign_shift_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="workassignment",
            index=models.Index(fields=["status"], name="ix_assign_status"),
        ),
        migrations.AddIndex(
            model_name="workerskill",
            index=models.Index(
                fields=["operation_nm", "skill_level"], name="ix_skill_op_level"
            ),
        ),
        migrations.AddIndex(
            model_name="workerskill",
            index=models.Index(
                fields=["worker", "skill_level"], name="ix_skill_worker_level"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workerskill",
            unique_together={("worker", "operation_nm")},
        ),
    ]
