# Generated by Django 4.2.7 on 2026-01-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIRootCauseAnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_id",
                    models.CharField(help_text="분석 ID", max_length=50, unique=True),
                ),
                ("problem_description", models.TextField(help_text="문제 설명")),
                ("defect_details", models.TextField(help_text="불량 상세")),
                ("context", models.TextField(blank=True, help_text="추가 컨텍스트")),
                ("root_cause", models.TextField(help_text="근본 원인")),
                ("confidence", models.FloatField(help_text="신뢰도 (0-1)")),
                (
                    "recommended_corrective_actions",
                    models.JSONField(help_text="권장 시정 조치 (JSON)"),
                ),
                (
                    "recommended_preventive_actions",
                    models.JSONField(help_text="권장 예방 조치 (JSON)"),
                ),
                (
                    "is_applied",
                    models.BooleanField(default=False, help_text="적용 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Root Cause Analysis History",
                "verbose_name_plural": "AI Root Cause Analysis Histories",
                "db_table": "ai_root_cause_analysis_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Capa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capa_id",
                    models.CharField(help_text="CAPA ID", max_length=50, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("COMPLAINT", "고객 불만"),
                            ("AUDIT", "심사"),
                            ("OOS", "규격 이탈"),
                            ("SPC_EVENT", "SPC 이벤트"),
                        ],
                        help_text="출처 유형",
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(help_text="출처 ID", max_length=50)),
                ("title", models.CharField(help_text="제목", max_length=200)),
                ("description", models.TextField(help_text="설명")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "중대"),
                            ("MAJOR", "주요"),
                            ("MINOR", "경미"),
                        ],
                        help_text="심각도",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("VERIFICATION", "Verification"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="상태",
                        max_length=20,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(auto_now_add=True, help_text="개설일"),
                ),
                ("target_date", models.DateTimeField(help_text="목표일")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="완료일", null=True),
                ),
                ("assigned_to", models.CharField(help_text="담당자", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CAPA",
                "verbose_name_plural": "CAPAs",
                "db_table": "capa",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="QaProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qa_process_id",
                    models.CharField(
                        help_text="QA 프로세스 ID", max_length=50, unique=True
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("AUDIT", "심사"),
                            ("ASSESSMENT", "평가"),
                            ("REVIEW", "리뷰"),
                        ],
                        help_text="프로세스 유형",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="제목", max_length=200)),
                ("description", models.TextField(blank=True, help_text="설명")),
                ("scheduled_at", models.DateTimeField(help_text="예정일시")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "계획됨"),
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료됨"),
                        ],
                        default="PLANNED",
                        help_text="상태",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QA Process",
                "verbose_name_plural": "QA Processes",
                "db_table": "qa_process",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="QaFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_id",
                    models.CharField(
                        help_text="발견사항 ID", max_length=50, unique=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "중대"),
                            ("MAJOR", "주요"),
                            ("MINOR", "경미"),
                        ],
                        help_text="심각도",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="설명")),
                ("root_cause", models.TextField(blank=True, help_text="근본 원인")),
                (
                    "corrective_action",
                    models.TextField(blank=True, help_text="시정 조치"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, help_text="해결 여부"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="해결일시", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_process",
                    models.ForeignKey(
                        help_text="QA 프로세스",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="qa.qaprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Finding",
                "verbose_name_plural": "QA Findings",
                "db_table": "qa_finding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QaChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(help_text="아이템 ID", max_length=50, unique=True),
                ),
                (
                    "check_point",
                    models.CharField(help_text="체크포인트", max_length=200),
                ),
                ("requirement", models.TextField(help_text="요구사항")),
                (
                    "verification_method",
                    models.TextField(blank=True, help_text="검증 방법"),
                ),
                (
                    "is_compliant",
                    models.BooleanField(blank=True, help_text="준수 여부", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_process",
                    models.ForeignKey(
                        help_text="QA 프로세스",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="qa.qaprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Checklist Item",
                "verbose_name_plural": "QA Checklist Items",
                "db_table": "qa_checklist_item",
                "ordering": ["qa_process", "id"],
            },
        ),
        migrations.CreateModel(
            name="QaAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_id",
                    models.CharField(help_text="평가 ID", max_length=50, unique=True),
                ),
                ("assessed_at", models.DateTimeField(help_text="평가일시")),
                ("assessed_by", models.CharField(help_text="평가자 ID", max_length=50)),
                ("overall_score", models.FloatField(help_text="종합 점수")),
                ("conclusion", models.TextField(help_text="결론")),
                ("recommendations", models.TextField(blank=True, help_text="권고사항")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa_process",
                    models.ForeignKey(
                        help_text="QA 프로세스",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="qa.qaprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Assessment",
                "verbose_name_plural": "QA Assessments",
                "db_table": "qa_assessment",
                "ordering": ["-assessed_at"],
            },
        ),
        migrations.CreateModel(
            name="CapaAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_id",
                    models.CharField(help_text="조치 ID", max_length=50, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "시정 조치"),
                            ("PREVENTIVE", "예방 조치"),
                        ],
                        help_text="조치 유형",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="조치 설명")),
                ("assignee", models.CharField(help_text="담당자 ID", max_length=50)),
                ("due_date", models.DateField(help_text="목표일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료"),
                        ],
                        default="PENDING",
                        help_text="상태",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="완료일시", null=True),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, help_text="검증 비고"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capa",
                    models.ForeignKey(
                        help_text="CAPA",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="qa.capa",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAPA Action",
                "verbose_name_plural": "CAPA Actions",
                "db_table": "capa_action",
                "ordering": ["due_date"],
            },
        ),
    ]
