# Generated by Django 4.2.7 on 2026-01-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QCostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        help_text="카테고리 ID", max_length=50, unique=True
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("PREVENTION", "예방 비용"),
                            ("APPRAISAL", "평가 비용"),
                            ("INTERNAL_FAILURE", "내부 실패 비용"),
                            ("EXTERNAL_FAILURE", "외부 실패 비용"),
                        ],
                        help_text="카테고리 유형",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="카테고리명", max_length=100)),
                ("description", models.TextField(blank=True, help_text="설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Q-COST Category",
                "verbose_name_plural": "Q-COST Categories",
                "db_table": "qcost_category",
                "ordering": ["category_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="QCostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(help_text="아이템 ID", max_length=50, unique=True),
                ),
                ("code", models.CharField(help_text="아이템 코드", max_length=20)),
                ("name", models.CharField(help_text="아이템명", max_length=100)),
                ("unit", models.CharField(blank=True, help_text="단위", max_length=20)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="카테고리",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="qcost.qcostcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Q-COST Item",
                "verbose_name_plural": "Q-COST Items",
                "db_table": "qcost_item",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="QCostEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_id",
                    models.CharField(help_text="엔트리 ID", max_length=50, unique=True),
                ),
                ("occurred_at", models.DateTimeField(help_text="발생 일시")),
                ("quantity", models.FloatField(help_text="수량")),
                ("unit_cost", models.IntegerField(help_text="단가")),
                ("total_cost", models.IntegerField(help_text="총비용")),
                (
                    "reference_id",
                    models.CharField(blank=True, help_text="참조 ID", max_length=50),
                ),
                ("notes", models.TextField(blank=True, help_text="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        help_text="아이템",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="qcost.qcostitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Q-COST Entry",
                "verbose_name_plural": "Q-COST Entries",
                "db_table": "qcost_entry",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="AIClassificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification_id",
                    models.CharField(help_text="분류 ID", max_length=50, unique=True),
                ),
                ("description", models.TextField(help_text="비용 발생 상세 설명")),
                ("amount", models.IntegerField(help_text="비용 금액")),
                ("context", models.TextField(blank=True, help_text="추가 컨텍스트")),
                ("confidence", models.FloatField(help_text="신뢰도 (0-1)")),
                ("reasoning", models.TextField(help_text="분류 사유")),
                (
                    "is_applied",
                    models.BooleanField(default=False, help_text="적용 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_category",
                    models.ForeignKey(
                        help_text="제안된 카테고리",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_classifications",
                        to="qcost.qcostcategory",
                    ),
                ),
                (
                    "suggested_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="제안된 아이템",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_classifications",
                        to="qcost.qcostitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Classification History",
                "verbose_name_plural": "AI Classification Histories",
                "db_table": "ai_classification_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
