# Generated by Django 4.2.7 on 2026-01-14 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="설비 코드"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="설비명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CNC", "CNC 가공기"),
                            ("PRESS", "프레스"),
                            ("WELDING", "용접기"),
                            ("HEAT_TREAT", "열처리로"),
                            ("MEASUREMENT", "측정기"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="설비 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "가동 중"),
                            ("IDLE", "대기 중"),
                            ("MAINTENANCE", "점검 중"),
                            ("BREAKDOWN", "고장"),
                            ("RETIRED", "퇴역"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="설치 위치"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, verbose_name="제조사"),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=100, verbose_name="모델명"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="일련번호"
                    ),
                ),
                ("installation_date", models.DateField(verbose_name="설치일")),
                (
                    "warranty_expiry",
                    models.DateField(blank=True, null=True, verbose_name="보증 만료일"),
                ),
                (
                    "rated_capacity",
                    models.FloatField(blank=True, null=True, verbose_name="정격 용량"),
                ),
                (
                    "current_capacity",
                    models.FloatField(blank=True, null=True, verbose_name="현재 용량"),
                ),
                (
                    "mtbf_mean_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="MTBF (평균 고장 간격)"
                    ),
                ),
                (
                    "mttr_mean_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="MTTR (평균 수리 시간)"
                    ),
                ),
                (
                    "availability_target",
                    models.FloatField(default=95.0, verbose_name="가동률 목표 (%)"),
                ),
                (
                    "availability_current",
                    models.FloatField(
                        blank=True, null=True, verbose_name="현재 가동률 (%)"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 점검일"
                    ),
                ),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 점검예정일"
                    ),
                ),
                (
                    "failure_probability",
                    models.FloatField(default=0.0, verbose_name="고장 확률 (%)"),
                ),
                (
                    "health_score",
                    models.FloatField(default=100.0, verbose_name="건전도 점수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "설비",
                "verbose_name_plural": "설비",
                "db_table": "pm_equipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "예방 점검"),
                            ("PREDICTIVE", "예지 보전"),
                            ("CORRECTIVE", "고장 수리"),
                            ("EMERGENCY", "긴급 수리"),
                            ("OVERHAUL", "오버홀"),
                        ],
                        max_length=20,
                        verbose_name="점검 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "예정됨"),
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("scheduled_date", models.DateTimeField(verbose_name="예정일")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="인건비",
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="부품비",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="총비용",
                    ),
                ),
                (
                    "work_performed",
                    models.TextField(blank=True, verbose_name="수행 작업"),
                ),
                (
                    "parts_replaced",
                    models.TextField(blank=True, verbose_name="교체 부품"),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="근본 원인")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="권장사항"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="predictive_maintenance.equipment",
                        verbose_name="설비",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기술자",
                    ),
                ),
            ],
            options={
                "verbose_name": "점검 이력",
                "verbose_name_plural": "점검 이력",
                "db_table": "pm_maintenance_records",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="계획명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "일일"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("QUARTERLY", "분기"),
                            ("YEARLY", "연간"),
                            ("CUSTOM", "사용자 정의"),
                        ],
                        max_length=20,
                        verbose_name="빈도",
                    ),
                ),
                (
                    "frequency_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="주기 (일)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "활성"),
                            ("INACTIVE", "비활성"),
                            ("PAUSED", "일시중지"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("tasks", models.TextField(verbose_name="작업 내용")),
                (
                    "required_parts",
                    models.TextField(blank=True, verbose_name="필요 부품"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="예상 소요시간 (분)"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="예상 비용",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "last_performed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 수행일"
                    ),
                ),
                ("next_due_date", models.DateField(verbose_name="다음 예정일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_plans",
                        to="predictive_maintenance.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "예방 보전 계획",
                "verbose_name_plural": "예방 보전 계획",
                "db_table": "pm_maintenance_plans",
                "ordering": ["next_due_date"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("VIBRATION", "진동"),
                            ("TEMPERATURE", "온도"),
                            ("PRESSURE", "압력"),
                            ("CURRENT", "전류"),
                            ("VOLTAGE", "전압"),
                            ("SPEED", "속도"),
                            ("FLOW", "유량"),
                            ("NOISE", "소음"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="센서 유형",
                    ),
                ),
                ("sensor_id", models.CharField(max_length=100, verbose_name="센서 ID")),
                ("value", models.FloatField(verbose_name="측정값")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
                (
                    "threshold_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="최소 임계값"
                    ),
                ),
                (
                    "threshold_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="최대 임계값"
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="정상 여부"),
                ),
                (
                    "anomaly_score",
                    models.FloatField(default=0.0, verbose_name="이상 점수"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="측정 시간"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="predictive_maintenance.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "센서 데이터",
                "verbose_name_plural": "센서 데이터",
                "db_table": "pm_sensor_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["equipment", "-timestamp"],
                        name="pm_sensor_d_equipme_13c962_idx",
                    ),
                    models.Index(
                        fields=["sensor_type", "-timestamp"],
                        name="pm_sensor_d_sensor__889609_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FailurePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="예측일"),
                ),
                (
                    "predicted_failure_date",
                    models.DateTimeField(verbose_name="예측 고장일"),
                ),
                (
                    "failure_probability",
                    models.FloatField(verbose_name="고장 확률 (%)"),
                ),
                ("confidence", models.FloatField(verbose_name="신뢰도 (%)")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "중간"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "매우 높음"),
                        ],
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                ("potential_causes", models.TextField(verbose_name="잠재적 원인")),
                (
                    "affected_components",
                    models.TextField(blank=True, verbose_name="영향받는 부품"),
                ),
                ("recommended_actions", models.TextField(verbose_name="권장 조치")),
                ("priority", models.IntegerField(default=1, verbose_name="우선순위")),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="모델 버전"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="모델 유형"
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="확인 여부"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="확인일"),
                ),
                (
                    "actual_failure",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="실제 고장 여부"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="확인자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_predictions",
                        to="predictive_maintenance.equipment",
                        verbose_name="설비",
                    ),
                ),
            ],
            options={
                "verbose_name": "고장 예측",
                "verbose_name_plural": "고장 예측",
                "db_table": "pm_failure_predictions",
                "ordering": ["-prediction_date"],
                "indexes": [
                    models.Index(
                        fields=["equipment", "-prediction_date"],
                        name="pm_failure__equipme_67e3e5_idx",
                    ),
                    models.Index(
                        fields=["severity", "-prediction_date"],
                        name="pm_failure__severit_4d56ee_idx",
                    ),
                ],
            },
        ),
    ]
